// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: backend/protos/grade.proto

package grade

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages
type Grade struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	EnrollmentId   string                 `protobuf:"bytes,1,opt,name=enrollment_id,json=enrollmentId,proto3" json:"enrollment_id,omitempty"`
	StudentId      string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`       // denormalized
	StudentName    string                 `protobuf:"bytes,3,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"` // denormalized
	CourseId       string                 `protobuf:"bytes,4,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`          // denormalized
	CourseCode     string                 `protobuf:"bytes,5,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`    // denormalized
	CourseTitle    string                 `protobuf:"bytes,6,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"` // denormalized
	Units          int32                  `protobuf:"varint,7,opt,name=units,proto3" json:"units,omitempty"`                               // denormalized
	Grade          string                 `protobuf:"bytes,8,opt,name=grade,proto3" json:"grade,omitempty"`                                // A, B, C, D, F, I, W
	Semester       string                 `protobuf:"bytes,9,opt,name=semester,proto3" json:"semester,omitempty"`                          // denormalized
	UploadedBy     string                 `protobuf:"bytes,10,opt,name=uploaded_by,json=uploadedBy,proto3" json:"uploaded_by,omitempty"`
	UploadedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=uploaded_at,json=uploadedAt,proto3" json:"uploaded_at,omitempty"`
	Published      bool                   `protobuf:"varint,12,opt,name=published,proto3" json:"published,omitempty"`
	PublishedAt    *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=published_at,json=publishedAt,proto3" json:"published_at,omitempty"`
	OverrideReason string                 `protobuf:"bytes,14,opt,name=override_reason,json=overrideReason,proto3" json:"override_reason,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Grade) Reset() {
	*x = Grade{}
	mi := &file_backend_protos_grade_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grade) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grade) ProtoMessage() {}

func (x *Grade) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grade.ProtoReflect.Descriptor instead.
func (*Grade) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{0}
}

func (x *Grade) GetEnrollmentId() string {
	if x != nil {
		return x.EnrollmentId
	}
	return ""
}

func (x *Grade) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Grade) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *Grade) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Grade) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *Grade) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *Grade) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Grade) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

func (x *Grade) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *Grade) GetUploadedBy() string {
	if x != nil {
		return x.UploadedBy
	}
	return ""
}

func (x *Grade) GetUploadedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UploadedAt
	}
	return nil
}

func (x *Grade) GetPublished() bool {
	if x != nil {
		return x.Published
	}
	return false
}

func (x *Grade) GetPublishedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.PublishedAt
	}
	return nil
}

func (x *Grade) GetOverrideReason() string {
	if x != nil {
		return x.OverrideReason
	}
	return ""
}

type GPACalculation struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	TermGpa             float64                `protobuf:"fixed64,1,opt,name=term_gpa,json=termGpa,proto3" json:"term_gpa,omitempty"`
	Cgpa                float64                `protobuf:"fixed64,2,opt,name=cgpa,proto3" json:"cgpa,omitempty"`
	TotalUnitsAttempted int32                  `protobuf:"varint,3,opt,name=total_units_attempted,json=totalUnitsAttempted,proto3" json:"total_units_attempted,omitempty"`
	TotalUnitsEarned    int32                  `protobuf:"varint,4,opt,name=total_units_earned,json=totalUnitsEarned,proto3" json:"total_units_earned,omitempty"`
	SemesterBreakdown   []*SemesterGPA         `protobuf:"bytes,5,rep,name=semester_breakdown,json=semesterBreakdown,proto3" json:"semester_breakdown,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GPACalculation) Reset() {
	*x = GPACalculation{}
	mi := &file_backend_protos_grade_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GPACalculation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GPACalculation) ProtoMessage() {}

func (x *GPACalculation) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GPACalculation.ProtoReflect.Descriptor instead.
func (*GPACalculation) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{1}
}

func (x *GPACalculation) GetTermGpa() float64 {
	if x != nil {
		return x.TermGpa
	}
	return 0
}

func (x *GPACalculation) GetCgpa() float64 {
	if x != nil {
		return x.Cgpa
	}
	return 0
}

func (x *GPACalculation) GetTotalUnitsAttempted() int32 {
	if x != nil {
		return x.TotalUnitsAttempted
	}
	return 0
}

func (x *GPACalculation) GetTotalUnitsEarned() int32 {
	if x != nil {
		return x.TotalUnitsEarned
	}
	return 0
}

func (x *GPACalculation) GetSemesterBreakdown() []*SemesterGPA {
	if x != nil {
		return x.SemesterBreakdown
	}
	return nil
}

type SemesterGPA struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Semester      string                 `protobuf:"bytes,1,opt,name=semester,proto3" json:"semester,omitempty"`
	Gpa           float64                `protobuf:"fixed64,2,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Units         int32                  `protobuf:"varint,3,opt,name=units,proto3" json:"units,omitempty"`
	CoursesCount  int32                  `protobuf:"varint,4,opt,name=courses_count,json=coursesCount,proto3" json:"courses_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SemesterGPA) Reset() {
	*x = SemesterGPA{}
	mi := &file_backend_protos_grade_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SemesterGPA) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SemesterGPA) ProtoMessage() {}

func (x *SemesterGPA) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SemesterGPA.ProtoReflect.Descriptor instead.
func (*SemesterGPA) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{2}
}

func (x *SemesterGPA) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *SemesterGPA) GetGpa() float64 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *SemesterGPA) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *SemesterGPA) GetCoursesCount() int32 {
	if x != nil {
		return x.CoursesCount
	}
	return 0
}

type StudentRosterEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	StudentName   string                 `protobuf:"bytes,2,opt,name=student_name,json=studentName,proto3" json:"student_name,omitempty"`
	Email         string                 `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Major         string                 `protobuf:"bytes,4,opt,name=major,proto3" json:"major,omitempty"`
	YearLevel     int32                  `protobuf:"varint,5,opt,name=year_level,json=yearLevel,proto3" json:"year_level,omitempty"`
	Grade         string                 `protobuf:"bytes,6,opt,name=grade,proto3" json:"grade,omitempty"` // current grade if uploaded
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentRosterEntry) Reset() {
	*x = StudentRosterEntry{}
	mi := &file_backend_protos_grade_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentRosterEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentRosterEntry) ProtoMessage() {}

func (x *StudentRosterEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentRosterEntry.ProtoReflect.Descriptor instead.
func (*StudentRosterEntry) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{3}
}

func (x *StudentRosterEntry) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *StudentRosterEntry) GetStudentName() string {
	if x != nil {
		return x.StudentName
	}
	return ""
}

func (x *StudentRosterEntry) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentRosterEntry) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *StudentRosterEntry) GetYearLevel() int32 {
	if x != nil {
		return x.YearLevel
	}
	return 0
}

func (x *StudentRosterEntry) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

type GradeEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Grade         string                 `protobuf:"bytes,2,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradeEntry) Reset() {
	*x = GradeEntry{}
	mi := &file_backend_protos_grade_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradeEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradeEntry) ProtoMessage() {}

func (x *GradeEntry) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradeEntry.ProtoReflect.Descriptor instead.
func (*GradeEntry) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{4}
}

func (x *GradeEntry) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GradeEntry) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

// Request/Response messages
type GetStudentGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Semester      string                 `protobuf:"bytes,2,opt,name=semester,proto3" json:"semester,omitempty"` // optional filter
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGradesRequest) Reset() {
	*x = GetStudentGradesRequest{}
	mi := &file_backend_protos_grade_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGradesRequest) ProtoMessage() {}

func (x *GetStudentGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGradesRequest.ProtoReflect.Descriptor instead.
func (*GetStudentGradesRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{5}
}

func (x *GetStudentGradesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentGradesRequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type GetStudentGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*Grade               `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	GpaInfo       *GPACalculation        `protobuf:"bytes,2,opt,name=gpa_info,json=gpaInfo,proto3" json:"gpa_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentGradesResponse) Reset() {
	*x = GetStudentGradesResponse{}
	mi := &file_backend_protos_grade_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentGradesResponse) ProtoMessage() {}

func (x *GetStudentGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentGradesResponse.ProtoReflect.Descriptor instead.
func (*GetStudentGradesResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{6}
}

func (x *GetStudentGradesResponse) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

func (x *GetStudentGradesResponse) GetGpaInfo() *GPACalculation {
	if x != nil {
		return x.GpaInfo
	}
	return nil
}

type CalculateGPARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Semester      string                 `protobuf:"bytes,2,opt,name=semester,proto3" json:"semester,omitempty"` // optional, if empty calculates CGPA
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateGPARequest) Reset() {
	*x = CalculateGPARequest{}
	mi := &file_backend_protos_grade_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateGPARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateGPARequest) ProtoMessage() {}

func (x *CalculateGPARequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateGPARequest.ProtoReflect.Descriptor instead.
func (*CalculateGPARequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{7}
}

func (x *CalculateGPARequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CalculateGPARequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type CalculateGPAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GpaInfo       *GPACalculation        `protobuf:"bytes,2,opt,name=gpa_info,json=gpaInfo,proto3" json:"gpa_info,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalculateGPAResponse) Reset() {
	*x = CalculateGPAResponse{}
	mi := &file_backend_protos_grade_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalculateGPAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalculateGPAResponse) ProtoMessage() {}

func (x *CalculateGPAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalculateGPAResponse.ProtoReflect.Descriptor instead.
func (*CalculateGPAResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{8}
}

func (x *CalculateGPAResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CalculateGPAResponse) GetGpaInfo() *GPACalculation {
	if x != nil {
		return x.GpaInfo
	}
	return nil
}

func (x *CalculateGPAResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetClassRosterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassRosterRequest) Reset() {
	*x = GetClassRosterRequest{}
	mi := &file_backend_protos_grade_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassRosterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassRosterRequest) ProtoMessage() {}

func (x *GetClassRosterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassRosterRequest.ProtoReflect.Descriptor instead.
func (*GetClassRosterRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{9}
}

func (x *GetClassRosterRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetClassRosterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseCode    string                 `protobuf:"bytes,2,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseTitle   string                 `protobuf:"bytes,3,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Students      []*StudentRosterEntry  `protobuf:"bytes,4,rep,name=students,proto3" json:"students,omitempty"`
	TotalStudents int32                  `protobuf:"varint,5,opt,name=total_students,json=totalStudents,proto3" json:"total_students,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClassRosterResponse) Reset() {
	*x = GetClassRosterResponse{}
	mi := &file_backend_protos_grade_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClassRosterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClassRosterResponse) ProtoMessage() {}

func (x *GetClassRosterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClassRosterResponse.ProtoReflect.Descriptor instead.
func (*GetClassRosterResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{10}
}

func (x *GetClassRosterResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetClassRosterResponse) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *GetClassRosterResponse) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *GetClassRosterResponse) GetStudents() []*StudentRosterEntry {
	if x != nil {
		return x.Students
	}
	return nil
}

func (x *GetClassRosterResponse) GetTotalStudents() int32 {
	if x != nil {
		return x.TotalStudents
	}
	return 0
}

type UploadGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	FacultyId     string                 `protobuf:"bytes,2,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadGradesRequest) Reset() {
	*x = UploadGradesRequest{}
	mi := &file_backend_protos_grade_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadGradesRequest) ProtoMessage() {}

func (x *UploadGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadGradesRequest.ProtoReflect.Descriptor instead.
func (*UploadGradesRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{11}
}

func (x *UploadGradesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UploadGradesRequest) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

// Server streaming: Gateway sends grade entries one by one
type UploadGradeEntryRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*UploadGradeEntryRequest_Metadata
	//	*UploadGradeEntryRequest_Entry
	Payload       isUploadGradeEntryRequest_Payload `protobuf_oneof:"payload"`
	IsLast        bool                              `protobuf:"varint,3,opt,name=is_last,json=isLast,proto3" json:"is_last,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadGradeEntryRequest) Reset() {
	*x = UploadGradeEntryRequest{}
	mi := &file_backend_protos_grade_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadGradeEntryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadGradeEntryRequest) ProtoMessage() {}

func (x *UploadGradeEntryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadGradeEntryRequest.ProtoReflect.Descriptor instead.
func (*UploadGradeEntryRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{12}
}

func (x *UploadGradeEntryRequest) GetPayload() isUploadGradeEntryRequest_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *UploadGradeEntryRequest) GetMetadata() *UploadMetadata {
	if x != nil {
		if x, ok := x.Payload.(*UploadGradeEntryRequest_Metadata); ok {
			return x.Metadata
		}
	}
	return nil
}

func (x *UploadGradeEntryRequest) GetEntry() *GradeEntry {
	if x != nil {
		if x, ok := x.Payload.(*UploadGradeEntryRequest_Entry); ok {
			return x.Entry
		}
	}
	return nil
}

func (x *UploadGradeEntryRequest) GetIsLast() bool {
	if x != nil {
		return x.IsLast
	}
	return false
}

type isUploadGradeEntryRequest_Payload interface {
	isUploadGradeEntryRequest_Payload()
}

type UploadGradeEntryRequest_Metadata struct {
	Metadata *UploadMetadata `protobuf:"bytes,1,opt,name=metadata,proto3,oneof"` // First message only
}

type UploadGradeEntryRequest_Entry struct {
	Entry *GradeEntry `protobuf:"bytes,2,opt,name=entry,proto3,oneof"` // Subsequent messages
}

func (*UploadGradeEntryRequest_Metadata) isUploadGradeEntryRequest_Payload() {}

func (*UploadGradeEntryRequest_Entry) isUploadGradeEntryRequest_Payload() {}

type UploadMetadata struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	FacultyId     string                 `protobuf:"bytes,2,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadMetadata) Reset() {
	*x = UploadMetadata{}
	mi := &file_backend_protos_grade_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadMetadata) ProtoMessage() {}

func (x *UploadMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadMetadata.ProtoReflect.Descriptor instead.
func (*UploadMetadata) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{13}
}

func (x *UploadMetadata) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UploadMetadata) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

type UploadGradesResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	TotalProcessed int32                  `protobuf:"varint,2,opt,name=total_processed,json=totalProcessed,proto3" json:"total_processed,omitempty"`
	Successful     int32                  `protobuf:"varint,3,opt,name=successful,proto3" json:"successful,omitempty"`
	Failed         int32                  `protobuf:"varint,4,opt,name=failed,proto3" json:"failed,omitempty"`
	Errors         []string               `protobuf:"bytes,5,rep,name=errors,proto3" json:"errors,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UploadGradesResponse) Reset() {
	*x = UploadGradesResponse{}
	mi := &file_backend_protos_grade_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadGradesResponse) ProtoMessage() {}

func (x *UploadGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadGradesResponse.ProtoReflect.Descriptor instead.
func (*UploadGradesResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{14}
}

func (x *UploadGradesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UploadGradesResponse) GetTotalProcessed() int32 {
	if x != nil {
		return x.TotalProcessed
	}
	return 0
}

func (x *UploadGradesResponse) GetSuccessful() int32 {
	if x != nil {
		return x.Successful
	}
	return 0
}

func (x *UploadGradesResponse) GetFailed() int32 {
	if x != nil {
		return x.Failed
	}
	return 0
}

func (x *UploadGradesResponse) GetErrors() []string {
	if x != nil {
		return x.Errors
	}
	return nil
}

func (x *UploadGradesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type PublishGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	FacultyId     string                 `protobuf:"bytes,2,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PublishGradesRequest) Reset() {
	*x = PublishGradesRequest{}
	mi := &file_backend_protos_grade_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGradesRequest) ProtoMessage() {}

func (x *PublishGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGradesRequest.ProtoReflect.Descriptor instead.
func (*PublishGradesRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{15}
}

func (x *PublishGradesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *PublishGradesRequest) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

type PublishGradesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	GradesPublished int32                  `protobuf:"varint,2,opt,name=grades_published,json=gradesPublished,proto3" json:"grades_published,omitempty"`
	Message         string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *PublishGradesResponse) Reset() {
	*x = PublishGradesResponse{}
	mi := &file_backend_protos_grade_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PublishGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PublishGradesResponse) ProtoMessage() {}

func (x *PublishGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PublishGradesResponse.ProtoReflect.Descriptor instead.
func (*PublishGradesResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{16}
}

func (x *PublishGradesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *PublishGradesResponse) GetGradesPublished() int32 {
	if x != nil {
		return x.GradesPublished
	}
	return 0
}

func (x *PublishGradesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCourseGradesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	FacultyId     string                 `protobuf:"bytes,2,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"` // for authorization
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseGradesRequest) Reset() {
	*x = GetCourseGradesRequest{}
	mi := &file_backend_protos_grade_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseGradesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseGradesRequest) ProtoMessage() {}

func (x *GetCourseGradesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseGradesRequest.ProtoReflect.Descriptor instead.
func (*GetCourseGradesRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{17}
}

func (x *GetCourseGradesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *GetCourseGradesRequest) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

type GetCourseGradesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grades        []*Grade               `protobuf:"bytes,1,rep,name=grades,proto3" json:"grades,omitempty"`
	TotalGrades   int32                  `protobuf:"varint,2,opt,name=total_grades,json=totalGrades,proto3" json:"total_grades,omitempty"`
	AllPublished  bool                   `protobuf:"varint,3,opt,name=all_published,json=allPublished,proto3" json:"all_published,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseGradesResponse) Reset() {
	*x = GetCourseGradesResponse{}
	mi := &file_backend_protos_grade_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseGradesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseGradesResponse) ProtoMessage() {}

func (x *GetCourseGradesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_grade_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseGradesResponse.ProtoReflect.Descriptor instead.
func (*GetCourseGradesResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_grade_proto_rawDescGZIP(), []int{18}
}

func (x *GetCourseGradesResponse) GetGrades() []*Grade {
	if x != nil {
		return x.Grades
	}
	return nil
}

func (x *GetCourseGradesResponse) GetTotalGrades() int32 {
	if x != nil {
		return x.TotalGrades
	}
	return 0
}

func (x *GetCourseGradesResponse) GetAllPublished() bool {
	if x != nil {
		return x.AllPublished
	}
	return false
}

var File_backend_protos_grade_proto protoreflect.FileDescriptor

const file_backend_protos_grade_proto_rawDesc = "" +
	"\n" +
	"\x1abackend/protos/grade.proto\x12\x05grade\x1a\x1fgoogle/protobuf/timestamp.proto\"\xfb\x03\n" +
	"\x05Grade\x12#\n" +
	"\renrollment_id\x18\x01 \x01(\tR\fenrollmentId\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x03 \x01(\tR\vstudentName\x12\x1b\n" +
	"\tcourse_id\x18\x04 \x01(\tR\bcourseId\x12\x1f\n" +
	"\vcourse_code\x18\x05 \x01(\tR\n" +
	"courseCode\x12!\n" +
	"\fcourse_title\x18\x06 \x01(\tR\vcourseTitle\x12\x14\n" +
	"\x05units\x18\a \x01(\x05R\x05units\x12\x14\n" +
	"\x05grade\x18\b \x01(\tR\x05grade\x12\x1a\n" +
	"\bsemester\x18\t \x01(\tR\bsemester\x12\x1f\n" +
	"\vuploaded_by\x18\n" +
	" \x01(\tR\n" +
	"uploadedBy\x12;\n" +
	"\vuploaded_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"uploadedAt\x12\x1c\n" +
	"\tpublished\x18\f \x01(\bR\tpublished\x12=\n" +
	"\fpublished_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\vpublishedAt\x12'\n" +
	"\x0foverride_reason\x18\x0e \x01(\tR\x0eoverrideReason\"\xe4\x01\n" +
	"\x0eGPACalculation\x12\x19\n" +
	"\bterm_gpa\x18\x01 \x01(\x01R\atermGpa\x12\x12\n" +
	"\x04cgpa\x18\x02 \x01(\x01R\x04cgpa\x122\n" +
	"\x15total_units_attempted\x18\x03 \x01(\x05R\x13totalUnitsAttempted\x12,\n" +
	"\x12total_units_earned\x18\x04 \x01(\x05R\x10totalUnitsEarned\x12A\n" +
	"\x12semester_breakdown\x18\x05 \x03(\v2\x12.grade.SemesterGPAR\x11semesterBreakdown\"v\n" +
	"\vSemesterGPA\x12\x1a\n" +
	"\bsemester\x18\x01 \x01(\tR\bsemester\x12\x10\n" +
	"\x03gpa\x18\x02 \x01(\x01R\x03gpa\x12\x14\n" +
	"\x05units\x18\x03 \x01(\x05R\x05units\x12#\n" +
	"\rcourses_count\x18\x04 \x01(\x05R\fcoursesCount\"\xb7\x01\n" +
	"\x12StudentRosterEntry\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12!\n" +
	"\fstudent_name\x18\x02 \x01(\tR\vstudentName\x12\x14\n" +
	"\x05email\x18\x03 \x01(\tR\x05email\x12\x14\n" +
	"\x05major\x18\x04 \x01(\tR\x05major\x12\x1d\n" +
	"\n" +
	"year_level\x18\x05 \x01(\x05R\tyearLevel\x12\x14\n" +
	"\x05grade\x18\x06 \x01(\tR\x05grade\"A\n" +
	"\n" +
	"GradeEntry\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x14\n" +
	"\x05grade\x18\x02 \x01(\tR\x05grade\"T\n" +
	"\x17GetStudentGradesRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bsemester\x18\x02 \x01(\tR\bsemester\"r\n" +
	"\x18GetStudentGradesResponse\x12$\n" +
	"\x06grades\x18\x01 \x03(\v2\f.grade.GradeR\x06grades\x120\n" +
	"\bgpa_info\x18\x02 \x01(\v2\x15.grade.GPACalculationR\agpaInfo\"P\n" +
	"\x13CalculateGPARequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bsemester\x18\x02 \x01(\tR\bsemester\"|\n" +
	"\x14CalculateGPAResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x120\n" +
	"\bgpa_info\x18\x02 \x01(\v2\x15.grade.GPACalculationR\agpaInfo\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"4\n" +
	"\x15GetClassRosterRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\xd7\x01\n" +
	"\x16GetClassRosterResponse\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1f\n" +
	"\vcourse_code\x18\x02 \x01(\tR\n" +
	"courseCode\x12!\n" +
	"\fcourse_title\x18\x03 \x01(\tR\vcourseTitle\x125\n" +
	"\bstudents\x18\x04 \x03(\v2\x19.grade.StudentRosterEntryR\bstudents\x12%\n" +
	"\x0etotal_students\x18\x05 \x01(\x05R\rtotalStudents\"Q\n" +
	"\x13UploadGradesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x02 \x01(\tR\tfacultyId\"\x9d\x01\n" +
	"\x17UploadGradeEntryRequest\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x15.grade.UploadMetadataH\x00R\bmetadata\x12)\n" +
	"\x05entry\x18\x02 \x01(\v2\x11.grade.GradeEntryH\x00R\x05entry\x12\x17\n" +
	"\ais_last\x18\x03 \x01(\bR\x06isLastB\t\n" +
	"\apayload\"L\n" +
	"\x0eUploadMetadata\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x02 \x01(\tR\tfacultyId\"\xc3\x01\n" +
	"\x14UploadGradesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0ftotal_processed\x18\x02 \x01(\x05R\x0etotalProcessed\x12\x1e\n" +
	"\n" +
	"successful\x18\x03 \x01(\x05R\n" +
	"successful\x12\x16\n" +
	"\x06failed\x18\x04 \x01(\x05R\x06failed\x12\x16\n" +
	"\x06errors\x18\x05 \x03(\tR\x06errors\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage\"R\n" +
	"\x14PublishGradesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x02 \x01(\tR\tfacultyId\"v\n" +
	"\x15PublishGradesResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12)\n" +
	"\x10grades_published\x18\x02 \x01(\x05R\x0fgradesPublished\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"T\n" +
	"\x16GetCourseGradesRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x02 \x01(\tR\tfacultyId\"\x87\x01\n" +
	"\x17GetCourseGradesResponse\x12$\n" +
	"\x06grades\x18\x01 \x03(\v2\f.grade.GradeR\x06grades\x12!\n" +
	"\ftotal_grades\x18\x02 \x01(\x05R\vtotalGrades\x12#\n" +
	"\rall_published\x18\x03 \x01(\bR\fallPublished2\xe8\x03\n" +
	"\fGradeService\x12S\n" +
	"\x10GetStudentGrades\x12\x1e.grade.GetStudentGradesRequest\x1a\x1f.grade.GetStudentGradesResponse\x12G\n" +
	"\fCalculateGPA\x12\x1a.grade.CalculateGPARequest\x1a\x1b.grade.CalculateGPAResponse\x12M\n" +
	"\x0eGetClassRoster\x12\x1c.grade.GetClassRosterRequest\x1a\x1d.grade.GetClassRosterResponse\x12M\n" +
	"\fUploadGrades\x12\x1e.grade.UploadGradeEntryRequest\x1a\x1b.grade.UploadGradesResponse(\x01\x12J\n" +
	"\rPublishGrades\x12\x1b.grade.PublishGradesRequest\x1a\x1c.grade.PublishGradesResponse\x12P\n" +
	"\x0fGetCourseGrades\x12\x1d.grade.GetCourseGradesRequest\x1a\x1e.grade.GetCourseGradesResponseB\x12Z\x10backend/pb/gradeb\x06proto3"

var (
	file_backend_protos_grade_proto_rawDescOnce sync.Once
	file_backend_protos_grade_proto_rawDescData []byte
)

func file_backend_protos_grade_proto_rawDescGZIP() []byte {
	file_backend_protos_grade_proto_rawDescOnce.Do(func() {
		file_backend_protos_grade_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_protos_grade_proto_rawDesc), len(file_backend_protos_grade_proto_rawDesc)))
	})
	return file_backend_protos_grade_proto_rawDescData
}

var file_backend_protos_grade_proto_msgTypes = make([]protoimpl.MessageInfo, 19)
var file_backend_protos_grade_proto_goTypes = []any{
	(*Grade)(nil),                    // 0: grade.Grade
	(*GPACalculation)(nil),           // 1: grade.GPACalculation
	(*SemesterGPA)(nil),              // 2: grade.SemesterGPA
	(*StudentRosterEntry)(nil),       // 3: grade.StudentRosterEntry
	(*GradeEntry)(nil),               // 4: grade.GradeEntry
	(*GetStudentGradesRequest)(nil),  // 5: grade.GetStudentGradesRequest
	(*GetStudentGradesResponse)(nil), // 6: grade.GetStudentGradesResponse
	(*CalculateGPARequest)(nil),      // 7: grade.CalculateGPARequest
	(*CalculateGPAResponse)(nil),     // 8: grade.CalculateGPAResponse
	(*GetClassRosterRequest)(nil),    // 9: grade.GetClassRosterRequest
	(*GetClassRosterResponse)(nil),   // 10: grade.GetClassRosterResponse
	(*UploadGradesRequest)(nil),      // 11: grade.UploadGradesRequest
	(*UploadGradeEntryRequest)(nil),  // 12: grade.UploadGradeEntryRequest
	(*UploadMetadata)(nil),           // 13: grade.UploadMetadata
	(*UploadGradesResponse)(nil),     // 14: grade.UploadGradesResponse
	(*PublishGradesRequest)(nil),     // 15: grade.PublishGradesRequest
	(*PublishGradesResponse)(nil),    // 16: grade.PublishGradesResponse
	(*GetCourseGradesRequest)(nil),   // 17: grade.GetCourseGradesRequest
	(*GetCourseGradesResponse)(nil),  // 18: grade.GetCourseGradesResponse
	(*timestamppb.Timestamp)(nil),    // 19: google.protobuf.Timestamp
}
var file_backend_protos_grade_proto_depIdxs = []int32{
	19, // 0: grade.Grade.uploaded_at:type_name -> google.protobuf.Timestamp
	19, // 1: grade.Grade.published_at:type_name -> google.protobuf.Timestamp
	2,  // 2: grade.GPACalculation.semester_breakdown:type_name -> grade.SemesterGPA
	0,  // 3: grade.GetStudentGradesResponse.grades:type_name -> grade.Grade
	1,  // 4: grade.GetStudentGradesResponse.gpa_info:type_name -> grade.GPACalculation
	1,  // 5: grade.CalculateGPAResponse.gpa_info:type_name -> grade.GPACalculation
	3,  // 6: grade.GetClassRosterResponse.students:type_name -> grade.StudentRosterEntry
	13, // 7: grade.UploadGradeEntryRequest.metadata:type_name -> grade.UploadMetadata
	4,  // 8: grade.UploadGradeEntryRequest.entry:type_name -> grade.GradeEntry
	0,  // 9: grade.GetCourseGradesResponse.grades:type_name -> grade.Grade
	5,  // 10: grade.GradeService.GetStudentGrades:input_type -> grade.GetStudentGradesRequest
	7,  // 11: grade.GradeService.CalculateGPA:input_type -> grade.CalculateGPARequest
	9,  // 12: grade.GradeService.GetClassRoster:input_type -> grade.GetClassRosterRequest
	12, // 13: grade.GradeService.UploadGrades:input_type -> grade.UploadGradeEntryRequest
	15, // 14: grade.GradeService.PublishGrades:input_type -> grade.PublishGradesRequest
	17, // 15: grade.GradeService.GetCourseGrades:input_type -> grade.GetCourseGradesRequest
	6,  // 16: grade.GradeService.GetStudentGrades:output_type -> grade.GetStudentGradesResponse
	8,  // 17: grade.GradeService.CalculateGPA:output_type -> grade.CalculateGPAResponse
	10, // 18: grade.GradeService.GetClassRoster:output_type -> grade.GetClassRosterResponse
	14, // 19: grade.GradeService.UploadGrades:output_type -> grade.UploadGradesResponse
	16, // 20: grade.GradeService.PublishGrades:output_type -> grade.PublishGradesResponse
	18, // 21: grade.GradeService.GetCourseGrades:output_type -> grade.GetCourseGradesResponse
	16, // [16:22] is the sub-list for method output_type
	10, // [10:16] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_backend_protos_grade_proto_init() }
func file_backend_protos_grade_proto_init() {
	if File_backend_protos_grade_proto != nil {
		return
	}
	file_backend_protos_grade_proto_msgTypes[12].OneofWrappers = []any{
		(*UploadGradeEntryRequest_Metadata)(nil),
		(*UploadGradeEntryRequest_Entry)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_protos_grade_proto_rawDesc), len(file_backend_protos_grade_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   19,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_protos_grade_proto_goTypes,
		DependencyIndexes: file_backend_protos_grade_proto_depIdxs,
		MessageInfos:      file_backend_protos_grade_proto_msgTypes,
	}.Build()
	File_backend_protos_grade_proto = out.File
	file_backend_protos_grade_proto_goTypes = nil
	file_backend_protos_grade_proto_depIdxs = nil
}
