// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: backend/protos/enrollment.proto

package enrollment

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages
type ScheduleInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Days          []string               `protobuf:"bytes,1,rep,name=days,proto3" json:"days,omitempty"`                            // ["M", "W", "F"]
	StartTime     string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"` // "9:00"
	EndTime       string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`       // "10:00"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScheduleInfo) Reset() {
	*x = ScheduleInfo{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleInfo) ProtoMessage() {}

func (x *ScheduleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScheduleInfo.ProtoReflect.Descriptor instead.
func (*ScheduleInfo) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{0}
}

func (x *ScheduleInfo) GetDays() []string {
	if x != nil {
		return x.Days
	}
	return nil
}

func (x *ScheduleInfo) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *ScheduleInfo) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

type Enrollment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	StudentId     string                 `protobuf:"bytes,2,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,3,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseCode    string                 `protobuf:"bytes,4,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`    // denormalized
	CourseTitle   string                 `protobuf:"bytes,5,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"` // denormalized
	Units         int32                  `protobuf:"varint,6,opt,name=units,proto3" json:"units,omitempty"`                               // denormalized
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`                              // enrolled, dropped, completed
	EnrolledAt    *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=enrolled_at,json=enrolledAt,proto3" json:"enrolled_at,omitempty"`
	DroppedAt     *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=dropped_at,json=droppedAt,proto3" json:"dropped_at,omitempty"`
	ScheduleInfo  *ScheduleInfo          `protobuf:"bytes,10,opt,name=schedule_info,json=scheduleInfo,proto3" json:"schedule_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Enrollment) Reset() {
	*x = Enrollment{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Enrollment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Enrollment) ProtoMessage() {}

func (x *Enrollment) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Enrollment.ProtoReflect.Descriptor instead.
func (*Enrollment) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{1}
}

func (x *Enrollment) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Enrollment) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Enrollment) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *Enrollment) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *Enrollment) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *Enrollment) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Enrollment) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Enrollment) GetEnrolledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EnrolledAt
	}
	return nil
}

func (x *Enrollment) GetDroppedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DroppedAt
	}
	return nil
}

func (x *Enrollment) GetScheduleInfo() *ScheduleInfo {
	if x != nil {
		return x.ScheduleInfo
	}
	return nil
}

type CartItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseCode    string                 `protobuf:"bytes,2,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	CourseTitle   string                 `protobuf:"bytes,3,opt,name=course_title,json=courseTitle,proto3" json:"course_title,omitempty"`
	Units         int32                  `protobuf:"varint,4,opt,name=units,proto3" json:"units,omitempty"`
	ScheduleInfo  *ScheduleInfo          `protobuf:"bytes,5,opt,name=schedule_info,json=scheduleInfo,proto3" json:"schedule_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CartItem) Reset() {
	*x = CartItem{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CartItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CartItem) ProtoMessage() {}

func (x *CartItem) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CartItem.ProtoReflect.Descriptor instead.
func (*CartItem) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{2}
}

func (x *CartItem) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CartItem) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *CartItem) GetCourseTitle() string {
	if x != nil {
		return x.CourseTitle
	}
	return ""
}

func (x *CartItem) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *CartItem) GetScheduleInfo() *ScheduleInfo {
	if x != nil {
		return x.ScheduleInfo
	}
	return nil
}

type Cart struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StudentId            string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Items                []*CartItem            `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
	TotalUnits           int32                  `protobuf:"varint,3,opt,name=total_units,json=totalUnits,proto3" json:"total_units,omitempty"`
	HasConflicts         bool                   `protobuf:"varint,4,opt,name=has_conflicts,json=hasConflicts,proto3" json:"has_conflicts,omitempty"`
	MissingPrerequisites []string               `protobuf:"bytes,5,rep,name=missing_prerequisites,json=missingPrerequisites,proto3" json:"missing_prerequisites,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Cart) Reset() {
	*x = Cart{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cart) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cart) ProtoMessage() {}

func (x *Cart) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cart.ProtoReflect.Descriptor instead.
func (*Cart) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{3}
}

func (x *Cart) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *Cart) GetItems() []*CartItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *Cart) GetTotalUnits() int32 {
	if x != nil {
		return x.TotalUnits
	}
	return 0
}

func (x *Cart) GetHasConflicts() bool {
	if x != nil {
		return x.HasConflicts
	}
	return false
}

func (x *Cart) GetMissingPrerequisites() []string {
	if x != nil {
		return x.MissingPrerequisites
	}
	return nil
}

func (x *Cart) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Course1Id     string                 `protobuf:"bytes,1,opt,name=course1_id,json=course1Id,proto3" json:"course1_id,omitempty"`
	Course1Code   string                 `protobuf:"bytes,2,opt,name=course1_code,json=course1Code,proto3" json:"course1_code,omitempty"`
	Course2Id     string                 `protobuf:"bytes,3,opt,name=course2_id,json=course2Id,proto3" json:"course2_id,omitempty"`
	Course2Code   string                 `protobuf:"bytes,4,opt,name=course2_code,json=course2Code,proto3" json:"course2_code,omitempty"`
	ConflictType  string                 `protobuf:"bytes,5,opt,name=conflict_type,json=conflictType,proto3" json:"conflict_type,omitempty"` // "schedule", "duplicate"
	Details       string                 `protobuf:"bytes,6,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{4}
}

func (x *Conflict) GetCourse1Id() string {
	if x != nil {
		return x.Course1Id
	}
	return ""
}

func (x *Conflict) GetCourse1Code() string {
	if x != nil {
		return x.Course1Code
	}
	return ""
}

func (x *Conflict) GetCourse2Id() string {
	if x != nil {
		return x.Course2Id
	}
	return ""
}

func (x *Conflict) GetCourse2Code() string {
	if x != nil {
		return x.Course2Code
	}
	return ""
}

func (x *Conflict) GetConflictType() string {
	if x != nil {
		return x.ConflictType
	}
	return ""
}

func (x *Conflict) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

// Request/Response messages
type AddToCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartRequest) Reset() {
	*x = AddToCartRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartRequest) ProtoMessage() {}

func (x *AddToCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartRequest.ProtoReflect.Descriptor instead.
func (*AddToCartRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{5}
}

func (x *AddToCartRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *AddToCartRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type AddToCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cart          *Cart                  `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddToCartResponse) Reset() {
	*x = AddToCartResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddToCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddToCartResponse) ProtoMessage() {}

func (x *AddToCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddToCartResponse.ProtoReflect.Descriptor instead.
func (*AddToCartResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{6}
}

func (x *AddToCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AddToCartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *AddToCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type RemoveFromCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartRequest) Reset() {
	*x = RemoveFromCartRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartRequest) ProtoMessage() {}

func (x *RemoveFromCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartRequest.ProtoReflect.Descriptor instead.
func (*RemoveFromCartRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{7}
}

func (x *RemoveFromCartRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *RemoveFromCartRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type RemoveFromCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Cart          *Cart                  `protobuf:"bytes,3,opt,name=cart,proto3" json:"cart,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveFromCartResponse) Reset() {
	*x = RemoveFromCartResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveFromCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFromCartResponse) ProtoMessage() {}

func (x *RemoveFromCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFromCartResponse.ProtoReflect.Descriptor instead.
func (*RemoveFromCartResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveFromCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RemoveFromCartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RemoveFromCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

type GetCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartRequest) Reset() {
	*x = GetCartRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartRequest) ProtoMessage() {}

func (x *GetCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartRequest.ProtoReflect.Descriptor instead.
func (*GetCartRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{9}
}

func (x *GetCartRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type GetCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Cart          *Cart                  `protobuf:"bytes,2,opt,name=cart,proto3" json:"cart,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCartResponse) Reset() {
	*x = GetCartResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCartResponse) ProtoMessage() {}

func (x *GetCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCartResponse.ProtoReflect.Descriptor instead.
func (*GetCartResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{10}
}

func (x *GetCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCartResponse) GetCart() *Cart {
	if x != nil {
		return x.Cart
	}
	return nil
}

func (x *GetCartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ClearCartRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartRequest) Reset() {
	*x = ClearCartRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartRequest) ProtoMessage() {}

func (x *ClearCartRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartRequest.ProtoReflect.Descriptor instead.
func (*ClearCartRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{11}
}

func (x *ClearCartRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type ClearCartResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearCartResponse) Reset() {
	*x = ClearCartResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearCartResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearCartResponse) ProtoMessage() {}

func (x *ClearCartResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearCartResponse.ProtoReflect.Descriptor instead.
func (*ClearCartResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{12}
}

func (x *ClearCartResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClearCartResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckConflictsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseIds     []string               `protobuf:"bytes,2,rep,name=course_ids,json=courseIds,proto3" json:"course_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConflictsRequest) Reset() {
	*x = CheckConflictsRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConflictsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConflictsRequest) ProtoMessage() {}

func (x *CheckConflictsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConflictsRequest.ProtoReflect.Descriptor instead.
func (*CheckConflictsRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{13}
}

func (x *CheckConflictsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CheckConflictsRequest) GetCourseIds() []string {
	if x != nil {
		return x.CourseIds
	}
	return nil
}

type CheckConflictsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	HasConflicts  bool                   `protobuf:"varint,1,opt,name=has_conflicts,json=hasConflicts,proto3" json:"has_conflicts,omitempty"`
	Conflicts     []*Conflict            `protobuf:"bytes,2,rep,name=conflicts,proto3" json:"conflicts,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckConflictsResponse) Reset() {
	*x = CheckConflictsResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckConflictsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckConflictsResponse) ProtoMessage() {}

func (x *CheckConflictsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckConflictsResponse.ProtoReflect.Descriptor instead.
func (*CheckConflictsResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{14}
}

func (x *CheckConflictsResponse) GetHasConflicts() bool {
	if x != nil {
		return x.HasConflicts
	}
	return false
}

func (x *CheckConflictsResponse) GetConflicts() []*Conflict {
	if x != nil {
		return x.Conflicts
	}
	return nil
}

func (x *CheckConflictsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type EnrollAllRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollAllRequest) Reset() {
	*x = EnrollAllRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollAllRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollAllRequest) ProtoMessage() {}

func (x *EnrollAllRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollAllRequest.ProtoReflect.Descriptor instead.
func (*EnrollAllRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{15}
}

func (x *EnrollAllRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

type EnrollAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Enrollments   []*Enrollment          `protobuf:"bytes,3,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	FailedCourses []string               `protobuf:"bytes,4,rep,name=failed_courses,json=failedCourses,proto3" json:"failed_courses,omitempty"` // courses that failed to enroll
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollAllResponse) Reset() {
	*x = EnrollAllResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollAllResponse) ProtoMessage() {}

func (x *EnrollAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollAllResponse.ProtoReflect.Descriptor instead.
func (*EnrollAllResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{16}
}

func (x *EnrollAllResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *EnrollAllResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *EnrollAllResponse) GetEnrollments() []*Enrollment {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

func (x *EnrollAllResponse) GetFailedCourses() []string {
	if x != nil {
		return x.FailedCourses
	}
	return nil
}

type DropCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCourseRequest) Reset() {
	*x = DropCourseRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCourseRequest) ProtoMessage() {}

func (x *DropCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCourseRequest.ProtoReflect.Descriptor instead.
func (*DropCourseRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{17}
}

func (x *DropCourseRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *DropCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type DropCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropCourseResponse) Reset() {
	*x = DropCourseResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropCourseResponse) ProtoMessage() {}

func (x *DropCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropCourseResponse.ProtoReflect.Descriptor instead.
func (*DropCourseResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{18}
}

func (x *DropCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DropCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetStudentEnrollmentsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	Semester      string                 `protobuf:"bytes,2,opt,name=semester,proto3" json:"semester,omitempty"` // optional filter
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`     // optional filter: enrolled, dropped, completed
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentEnrollmentsRequest) Reset() {
	*x = GetStudentEnrollmentsRequest{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentEnrollmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentEnrollmentsRequest) ProtoMessage() {}

func (x *GetStudentEnrollmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentEnrollmentsRequest.ProtoReflect.Descriptor instead.
func (*GetStudentEnrollmentsRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{19}
}

func (x *GetStudentEnrollmentsRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *GetStudentEnrollmentsRequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *GetStudentEnrollmentsRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type GetStudentEnrollmentsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enrollments   []*Enrollment          `protobuf:"bytes,1,rep,name=enrollments,proto3" json:"enrollments,omitempty"`
	TotalUnits    int32                  `protobuf:"varint,2,opt,name=total_units,json=totalUnits,proto3" json:"total_units,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStudentEnrollmentsResponse) Reset() {
	*x = GetStudentEnrollmentsResponse{}
	mi := &file_backend_protos_enrollment_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStudentEnrollmentsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStudentEnrollmentsResponse) ProtoMessage() {}

func (x *GetStudentEnrollmentsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_enrollment_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStudentEnrollmentsResponse.ProtoReflect.Descriptor instead.
func (*GetStudentEnrollmentsResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_enrollment_proto_rawDescGZIP(), []int{20}
}

func (x *GetStudentEnrollmentsResponse) GetEnrollments() []*Enrollment {
	if x != nil {
		return x.Enrollments
	}
	return nil
}

func (x *GetStudentEnrollmentsResponse) GetTotalUnits() int32 {
	if x != nil {
		return x.TotalUnits
	}
	return 0
}

var File_backend_protos_enrollment_proto protoreflect.FileDescriptor

const file_backend_protos_enrollment_proto_rawDesc = "" +
	"\n" +
	"\x1fbackend/protos/enrollment.proto\x12\n" +
	"enrollment\x1a\x1fgoogle/protobuf/timestamp.proto\"\\\n" +
	"\fScheduleInfo\x12\x12\n" +
	"\x04days\x18\x01 \x03(\tR\x04days\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\"\x81\x03\n" +
	"\n" +
	"Enrollment\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"student_id\x18\x02 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x03 \x01(\tR\bcourseId\x12\x1f\n" +
	"\vcourse_code\x18\x04 \x01(\tR\n" +
	"courseCode\x12!\n" +
	"\fcourse_title\x18\x05 \x01(\tR\vcourseTitle\x12\x14\n" +
	"\x05units\x18\x06 \x01(\x05R\x05units\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12;\n" +
	"\venrolled_at\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"enrolledAt\x129\n" +
	"\n" +
	"dropped_at\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\tdroppedAt\x12=\n" +
	"\rschedule_info\x18\n" +
	" \x01(\v2\x18.enrollment.ScheduleInfoR\fscheduleInfo\"\xc0\x01\n" +
	"\bCartItem\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1f\n" +
	"\vcourse_code\x18\x02 \x01(\tR\n" +
	"courseCode\x12!\n" +
	"\fcourse_title\x18\x03 \x01(\tR\vcourseTitle\x12\x14\n" +
	"\x05units\x18\x04 \x01(\x05R\x05units\x12=\n" +
	"\rschedule_info\x18\x05 \x01(\v2\x18.enrollment.ScheduleInfoR\fscheduleInfo\"\x87\x02\n" +
	"\x04Cart\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12*\n" +
	"\x05items\x18\x02 \x03(\v2\x14.enrollment.CartItemR\x05items\x12\x1f\n" +
	"\vtotal_units\x18\x03 \x01(\x05R\n" +
	"totalUnits\x12#\n" +
	"\rhas_conflicts\x18\x04 \x01(\bR\fhasConflicts\x123\n" +
	"\x15missing_prerequisites\x18\x05 \x03(\tR\x14missingPrerequisites\x129\n" +
	"\n" +
	"updated_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\xcd\x01\n" +
	"\bConflict\x12\x1d\n" +
	"\n" +
	"course1_id\x18\x01 \x01(\tR\tcourse1Id\x12!\n" +
	"\fcourse1_code\x18\x02 \x01(\tR\vcourse1Code\x12\x1d\n" +
	"\n" +
	"course2_id\x18\x03 \x01(\tR\tcourse2Id\x12!\n" +
	"\fcourse2_code\x18\x04 \x01(\tR\vcourse2Code\x12#\n" +
	"\rconflict_type\x18\x05 \x01(\tR\fconflictType\x12\x18\n" +
	"\adetails\x18\x06 \x01(\tR\adetails\"N\n" +
	"\x10AddToCartRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"m\n" +
	"\x11AddToCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04cart\x18\x03 \x01(\v2\x10.enrollment.CartR\x04cart\"S\n" +
	"\x15RemoveFromCartRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"r\n" +
	"\x16RemoveFromCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12$\n" +
	"\x04cart\x18\x03 \x01(\v2\x10.enrollment.CartR\x04cart\"/\n" +
	"\x0eGetCartRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"k\n" +
	"\x0fGetCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12$\n" +
	"\x04cart\x18\x02 \x01(\v2\x10.enrollment.CartR\x04cart\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"1\n" +
	"\x10ClearCartRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"G\n" +
	"\x11ClearCartResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"U\n" +
	"\x15CheckConflictsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"course_ids\x18\x02 \x03(\tR\tcourseIds\"\x8b\x01\n" +
	"\x16CheckConflictsResponse\x12#\n" +
	"\rhas_conflicts\x18\x01 \x01(\bR\fhasConflicts\x122\n" +
	"\tconflicts\x18\x02 \x03(\v2\x14.enrollment.ConflictR\tconflicts\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"1\n" +
	"\x10EnrollAllRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\"\xa8\x01\n" +
	"\x11EnrollAllResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x128\n" +
	"\venrollments\x18\x03 \x03(\v2\x16.enrollment.EnrollmentR\venrollments\x12%\n" +
	"\x0efailed_courses\x18\x04 \x03(\tR\rfailedCourses\"O\n" +
	"\x11DropCourseRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"H\n" +
	"\x12DropCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"q\n" +
	"\x1cGetStudentEnrollmentsRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1a\n" +
	"\bsemester\x18\x02 \x01(\tR\bsemester\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"z\n" +
	"\x1dGetStudentEnrollmentsResponse\x128\n" +
	"\venrollments\x18\x01 \x03(\v2\x16.enrollment.EnrollmentR\venrollments\x12\x1f\n" +
	"\vtotal_units\x18\x02 \x01(\x05R\n" +
	"totalUnits2\xa2\x05\n" +
	"\x11EnrollmentService\x12H\n" +
	"\tAddToCart\x12\x1c.enrollment.AddToCartRequest\x1a\x1d.enrollment.AddToCartResponse\x12W\n" +
	"\x0eRemoveFromCart\x12!.enrollment.RemoveFromCartRequest\x1a\".enrollment.RemoveFromCartResponse\x12B\n" +
	"\aGetCart\x12\x1a.enrollment.GetCartRequest\x1a\x1b.enrollment.GetCartResponse\x12H\n" +
	"\tClearCart\x12\x1c.enrollment.ClearCartRequest\x1a\x1d.enrollment.ClearCartResponse\x12W\n" +
	"\x0eCheckConflicts\x12!.enrollment.CheckConflictsRequest\x1a\".enrollment.CheckConflictsResponse\x12H\n" +
	"\tEnrollAll\x12\x1c.enrollment.EnrollAllRequest\x1a\x1d.enrollment.EnrollAllResponse\x12K\n" +
	"\n" +
	"DropCourse\x12\x1d.enrollment.DropCourseRequest\x1a\x1e.enrollment.DropCourseResponse\x12l\n" +
	"\x15GetStudentEnrollments\x12(.enrollment.GetStudentEnrollmentsRequest\x1a).enrollment.GetStudentEnrollmentsResponseB\x17Z\x15backend/pb/enrollmentb\x06proto3"

var (
	file_backend_protos_enrollment_proto_rawDescOnce sync.Once
	file_backend_protos_enrollment_proto_rawDescData []byte
)

func file_backend_protos_enrollment_proto_rawDescGZIP() []byte {
	file_backend_protos_enrollment_proto_rawDescOnce.Do(func() {
		file_backend_protos_enrollment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_protos_enrollment_proto_rawDesc), len(file_backend_protos_enrollment_proto_rawDesc)))
	})
	return file_backend_protos_enrollment_proto_rawDescData
}

var file_backend_protos_enrollment_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_backend_protos_enrollment_proto_goTypes = []any{
	(*ScheduleInfo)(nil),                  // 0: enrollment.ScheduleInfo
	(*Enrollment)(nil),                    // 1: enrollment.Enrollment
	(*CartItem)(nil),                      // 2: enrollment.CartItem
	(*Cart)(nil),                          // 3: enrollment.Cart
	(*Conflict)(nil),                      // 4: enrollment.Conflict
	(*AddToCartRequest)(nil),              // 5: enrollment.AddToCartRequest
	(*AddToCartResponse)(nil),             // 6: enrollment.AddToCartResponse
	(*RemoveFromCartRequest)(nil),         // 7: enrollment.RemoveFromCartRequest
	(*RemoveFromCartResponse)(nil),        // 8: enrollment.RemoveFromCartResponse
	(*GetCartRequest)(nil),                // 9: enrollment.GetCartRequest
	(*GetCartResponse)(nil),               // 10: enrollment.GetCartResponse
	(*ClearCartRequest)(nil),              // 11: enrollment.ClearCartRequest
	(*ClearCartResponse)(nil),             // 12: enrollment.ClearCartResponse
	(*CheckConflictsRequest)(nil),         // 13: enrollment.CheckConflictsRequest
	(*CheckConflictsResponse)(nil),        // 14: enrollment.CheckConflictsResponse
	(*EnrollAllRequest)(nil),              // 15: enrollment.EnrollAllRequest
	(*EnrollAllResponse)(nil),             // 16: enrollment.EnrollAllResponse
	(*DropCourseRequest)(nil),             // 17: enrollment.DropCourseRequest
	(*DropCourseResponse)(nil),            // 18: enrollment.DropCourseResponse
	(*GetStudentEnrollmentsRequest)(nil),  // 19: enrollment.GetStudentEnrollmentsRequest
	(*GetStudentEnrollmentsResponse)(nil), // 20: enrollment.GetStudentEnrollmentsResponse
	(*timestamppb.Timestamp)(nil),         // 21: google.protobuf.Timestamp
}
var file_backend_protos_enrollment_proto_depIdxs = []int32{
	21, // 0: enrollment.Enrollment.enrolled_at:type_name -> google.protobuf.Timestamp
	21, // 1: enrollment.Enrollment.dropped_at:type_name -> google.protobuf.Timestamp
	0,  // 2: enrollment.Enrollment.schedule_info:type_name -> enrollment.ScheduleInfo
	0,  // 3: enrollment.CartItem.schedule_info:type_name -> enrollment.ScheduleInfo
	2,  // 4: enrollment.Cart.items:type_name -> enrollment.CartItem
	21, // 5: enrollment.Cart.updated_at:type_name -> google.protobuf.Timestamp
	3,  // 6: enrollment.AddToCartResponse.cart:type_name -> enrollment.Cart
	3,  // 7: enrollment.RemoveFromCartResponse.cart:type_name -> enrollment.Cart
	3,  // 8: enrollment.GetCartResponse.cart:type_name -> enrollment.Cart
	4,  // 9: enrollment.CheckConflictsResponse.conflicts:type_name -> enrollment.Conflict
	1,  // 10: enrollment.EnrollAllResponse.enrollments:type_name -> enrollment.Enrollment
	1,  // 11: enrollment.GetStudentEnrollmentsResponse.enrollments:type_name -> enrollment.Enrollment
	5,  // 12: enrollment.EnrollmentService.AddToCart:input_type -> enrollment.AddToCartRequest
	7,  // 13: enrollment.EnrollmentService.RemoveFromCart:input_type -> enrollment.RemoveFromCartRequest
	9,  // 14: enrollment.EnrollmentService.GetCart:input_type -> enrollment.GetCartRequest
	11, // 15: enrollment.EnrollmentService.ClearCart:input_type -> enrollment.ClearCartRequest
	13, // 16: enrollment.EnrollmentService.CheckConflicts:input_type -> enrollment.CheckConflictsRequest
	15, // 17: enrollment.EnrollmentService.EnrollAll:input_type -> enrollment.EnrollAllRequest
	17, // 18: enrollment.EnrollmentService.DropCourse:input_type -> enrollment.DropCourseRequest
	19, // 19: enrollment.EnrollmentService.GetStudentEnrollments:input_type -> enrollment.GetStudentEnrollmentsRequest
	6,  // 20: enrollment.EnrollmentService.AddToCart:output_type -> enrollment.AddToCartResponse
	8,  // 21: enrollment.EnrollmentService.RemoveFromCart:output_type -> enrollment.RemoveFromCartResponse
	10, // 22: enrollment.EnrollmentService.GetCart:output_type -> enrollment.GetCartResponse
	12, // 23: enrollment.EnrollmentService.ClearCart:output_type -> enrollment.ClearCartResponse
	14, // 24: enrollment.EnrollmentService.CheckConflicts:output_type -> enrollment.CheckConflictsResponse
	16, // 25: enrollment.EnrollmentService.EnrollAll:output_type -> enrollment.EnrollAllResponse
	18, // 26: enrollment.EnrollmentService.DropCourse:output_type -> enrollment.DropCourseResponse
	20, // 27: enrollment.EnrollmentService.GetStudentEnrollments:output_type -> enrollment.GetStudentEnrollmentsResponse
	20, // [20:28] is the sub-list for method output_type
	12, // [12:20] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_backend_protos_enrollment_proto_init() }
func file_backend_protos_enrollment_proto_init() {
	if File_backend_protos_enrollment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_protos_enrollment_proto_rawDesc), len(file_backend_protos_enrollment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_protos_enrollment_proto_goTypes,
		DependencyIndexes: file_backend_protos_enrollment_proto_depIdxs,
		MessageInfos:      file_backend_protos_enrollment_proto_msgTypes,
	}.Build()
	File_backend_protos_enrollment_proto = out.File
	file_backend_protos_enrollment_proto_goTypes = nil
	file_backend_protos_enrollment_proto_depIdxs = nil
}
