// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: backend/protos/grade.proto

package grade

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	GradeService_GetStudentGrades_FullMethodName = "/grade.GradeService/GetStudentGrades"
	GradeService_CalculateGPA_FullMethodName     = "/grade.GradeService/CalculateGPA"
	GradeService_GetClassRoster_FullMethodName   = "/grade.GradeService/GetClassRoster"
	GradeService_UploadGrades_FullMethodName     = "/grade.GradeService/UploadGrades"
	GradeService_PublishGrades_FullMethodName    = "/grade.GradeService/PublishGrades"
	GradeService_GetCourseGrades_FullMethodName  = "/grade.GradeService/GetCourseGrades"
)

// GradeServiceClient is the client API for GradeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service definition
type GradeServiceClient interface {
	GetStudentGrades(ctx context.Context, in *GetStudentGradesRequest, opts ...grpc.CallOption) (*GetStudentGradesResponse, error)
	CalculateGPA(ctx context.Context, in *CalculateGPARequest, opts ...grpc.CallOption) (*CalculateGPAResponse, error)
	GetClassRoster(ctx context.Context, in *GetClassRosterRequest, opts ...grpc.CallOption) (*GetClassRosterResponse, error)
	// Client streaming: Gateway streams grade entries to service
	UploadGrades(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadGradeEntryRequest, UploadGradesResponse], error)
	PublishGrades(ctx context.Context, in *PublishGradesRequest, opts ...grpc.CallOption) (*PublishGradesResponse, error)
	GetCourseGrades(ctx context.Context, in *GetCourseGradesRequest, opts ...grpc.CallOption) (*GetCourseGradesResponse, error)
}

type gradeServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGradeServiceClient(cc grpc.ClientConnInterface) GradeServiceClient {
	return &gradeServiceClient{cc}
}

func (c *gradeServiceClient) GetStudentGrades(ctx context.Context, in *GetStudentGradesRequest, opts ...grpc.CallOption) (*GetStudentGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStudentGradesResponse)
	err := c.cc.Invoke(ctx, GradeService_GetStudentGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradeServiceClient) CalculateGPA(ctx context.Context, in *CalculateGPARequest, opts ...grpc.CallOption) (*CalculateGPAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CalculateGPAResponse)
	err := c.cc.Invoke(ctx, GradeService_CalculateGPA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradeServiceClient) GetClassRoster(ctx context.Context, in *GetClassRosterRequest, opts ...grpc.CallOption) (*GetClassRosterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClassRosterResponse)
	err := c.cc.Invoke(ctx, GradeService_GetClassRoster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradeServiceClient) UploadGrades(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadGradeEntryRequest, UploadGradesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &GradeService_ServiceDesc.Streams[0], GradeService_UploadGrades_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadGradeEntryRequest, UploadGradesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GradeService_UploadGradesClient = grpc.ClientStreamingClient[UploadGradeEntryRequest, UploadGradesResponse]

func (c *gradeServiceClient) PublishGrades(ctx context.Context, in *PublishGradesRequest, opts ...grpc.CallOption) (*PublishGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishGradesResponse)
	err := c.cc.Invoke(ctx, GradeService_PublishGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gradeServiceClient) GetCourseGrades(ctx context.Context, in *GetCourseGradesRequest, opts ...grpc.CallOption) (*GetCourseGradesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCourseGradesResponse)
	err := c.cc.Invoke(ctx, GradeService_GetCourseGrades_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GradeServiceServer is the server API for GradeService service.
// All implementations must embed UnimplementedGradeServiceServer
// for forward compatibility.
//
// Service definition
type GradeServiceServer interface {
	GetStudentGrades(context.Context, *GetStudentGradesRequest) (*GetStudentGradesResponse, error)
	CalculateGPA(context.Context, *CalculateGPARequest) (*CalculateGPAResponse, error)
	GetClassRoster(context.Context, *GetClassRosterRequest) (*GetClassRosterResponse, error)
	// Client streaming: Gateway streams grade entries to service
	UploadGrades(grpc.ClientStreamingServer[UploadGradeEntryRequest, UploadGradesResponse]) error
	PublishGrades(context.Context, *PublishGradesRequest) (*PublishGradesResponse, error)
	GetCourseGrades(context.Context, *GetCourseGradesRequest) (*GetCourseGradesResponse, error)
	mustEmbedUnimplementedGradeServiceServer()
}

// UnimplementedGradeServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGradeServiceServer struct{}

func (UnimplementedGradeServiceServer) GetStudentGrades(context.Context, *GetStudentGradesRequest) (*GetStudentGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStudentGrades not implemented")
}
func (UnimplementedGradeServiceServer) CalculateGPA(context.Context, *CalculateGPARequest) (*CalculateGPAResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CalculateGPA not implemented")
}
func (UnimplementedGradeServiceServer) GetClassRoster(context.Context, *GetClassRosterRequest) (*GetClassRosterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClassRoster not implemented")
}
func (UnimplementedGradeServiceServer) UploadGrades(grpc.ClientStreamingServer[UploadGradeEntryRequest, UploadGradesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadGrades not implemented")
}
func (UnimplementedGradeServiceServer) PublishGrades(context.Context, *PublishGradesRequest) (*PublishGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PublishGrades not implemented")
}
func (UnimplementedGradeServiceServer) GetCourseGrades(context.Context, *GetCourseGradesRequest) (*GetCourseGradesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCourseGrades not implemented")
}
func (UnimplementedGradeServiceServer) mustEmbedUnimplementedGradeServiceServer() {}
func (UnimplementedGradeServiceServer) testEmbeddedByValue()                      {}

// UnsafeGradeServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GradeServiceServer will
// result in compilation errors.
type UnsafeGradeServiceServer interface {
	mustEmbedUnimplementedGradeServiceServer()
}

func RegisterGradeServiceServer(s grpc.ServiceRegistrar, srv GradeServiceServer) {
	// If the following call pancis, it indicates UnimplementedGradeServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&GradeService_ServiceDesc, srv)
}

func _GradeService_GetStudentGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStudentGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradeServiceServer).GetStudentGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradeService_GetStudentGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradeServiceServer).GetStudentGrades(ctx, req.(*GetStudentGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradeService_CalculateGPA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculateGPARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradeServiceServer).CalculateGPA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradeService_CalculateGPA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradeServiceServer).CalculateGPA(ctx, req.(*CalculateGPARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradeService_GetClassRoster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClassRosterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradeServiceServer).GetClassRoster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradeService_GetClassRoster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradeServiceServer).GetClassRoster(ctx, req.(*GetClassRosterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradeService_UploadGrades_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GradeServiceServer).UploadGrades(&grpc.GenericServerStream[UploadGradeEntryRequest, UploadGradesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type GradeService_UploadGradesServer = grpc.ClientStreamingServer[UploadGradeEntryRequest, UploadGradesResponse]

func _GradeService_PublishGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradeServiceServer).PublishGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradeService_PublishGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradeServiceServer).PublishGrades(ctx, req.(*PublishGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GradeService_GetCourseGrades_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCourseGradesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GradeServiceServer).GetCourseGrades(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GradeService_GetCourseGrades_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GradeServiceServer).GetCourseGrades(ctx, req.(*GetCourseGradesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GradeService_ServiceDesc is the grpc.ServiceDesc for GradeService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GradeService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "grade.GradeService",
	HandlerType: (*GradeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStudentGrades",
			Handler:    _GradeService_GetStudentGrades_Handler,
		},
		{
			MethodName: "CalculateGPA",
			Handler:    _GradeService_CalculateGPA_Handler,
		},
		{
			MethodName: "GetClassRoster",
			Handler:    _GradeService_GetClassRoster_Handler,
		},
		{
			MethodName: "PublishGrades",
			Handler:    _GradeService_PublishGrades_Handler,
		},
		{
			MethodName: "GetCourseGrades",
			Handler:    _GradeService_GetCourseGrades_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadGrades",
			Handler:       _GradeService_UploadGrades_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "backend/protos/grade.proto",
}
