// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: backend/protos/admin.proto

package admin

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages (reusing some from other services)
type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Units         int32                  `protobuf:"varint,5,opt,name=units,proto3" json:"units,omitempty"`
	Schedule      string                 `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Room          string                 `protobuf:"bytes,7,opt,name=room,proto3" json:"room,omitempty"`
	Capacity      int32                  `protobuf:"varint,8,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enrolled      int32                  `protobuf:"varint,9,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	FacultyId     string                 `protobuf:"bytes,10,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	IsOpen        bool                   `protobuf:"varint,11,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	Semester      string                 `protobuf:"bytes,12,opt,name=semester,proto3" json:"semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_backend_protos_admin_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Course) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Course) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Course) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Course) GetEnrolled() int32 {
	if x != nil {
		return x.Enrolled
	}
	return 0
}

func (x *Course) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *Course) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *Course) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Email         string                 `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	StudentId     string                 `protobuf:"bytes,5,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	FacultyId     string                 `protobuf:"bytes,6,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	Department    string                 `protobuf:"bytes,7,opt,name=department,proto3" json:"department,omitempty"`
	Major         string                 `protobuf:"bytes,8,opt,name=major,proto3" json:"major,omitempty"`
	YearLevel     int32                  `protobuf:"varint,9,opt,name=year_level,json=yearLevel,proto3" json:"year_level,omitempty"`
	IsActive      bool                   `protobuf:"varint,10,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_backend_protos_admin_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{1}
}

func (x *User) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *User) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *User) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *User) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *User) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *User) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *User) GetYearLevel() int32 {
	if x != nil {
		return x.YearLevel
	}
	return 0
}

func (x *User) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *User) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SystemConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	UpdatedBy     string                 `protobuf:"bytes,4,opt,name=updated_by,json=updatedBy,proto3" json:"updated_by,omitempty"`
	Description   string                 `protobuf:"bytes,5,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemConfig) Reset() {
	*x = SystemConfig{}
	mi := &file_backend_protos_admin_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemConfig) ProtoMessage() {}

func (x *SystemConfig) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemConfig.ProtoReflect.Descriptor instead.
func (*SystemConfig) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{2}
}

func (x *SystemConfig) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *SystemConfig) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SystemConfig) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *SystemConfig) GetUpdatedBy() string {
	if x != nil {
		return x.UpdatedBy
	}
	return ""
}

func (x *SystemConfig) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type SystemStats struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TotalStudents    int32                  `protobuf:"varint,1,opt,name=total_students,json=totalStudents,proto3" json:"total_students,omitempty"`
	TotalFaculty     int32                  `protobuf:"varint,2,opt,name=total_faculty,json=totalFaculty,proto3" json:"total_faculty,omitempty"`
	TotalCourses     int32                  `protobuf:"varint,3,opt,name=total_courses,json=totalCourses,proto3" json:"total_courses,omitempty"`
	OpenCourses      int32                  `protobuf:"varint,4,opt,name=open_courses,json=openCourses,proto3" json:"open_courses,omitempty"`
	TotalEnrollments int32                  `protobuf:"varint,5,opt,name=total_enrollments,json=totalEnrollments,proto3" json:"total_enrollments,omitempty"`
	EnrollmentOpen   bool                   `protobuf:"varint,6,opt,name=enrollment_open,json=enrollmentOpen,proto3" json:"enrollment_open,omitempty"`
	CurrentSemester  string                 `protobuf:"bytes,7,opt,name=current_semester,json=currentSemester,proto3" json:"current_semester,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *SystemStats) Reset() {
	*x = SystemStats{}
	mi := &file_backend_protos_admin_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemStats) ProtoMessage() {}

func (x *SystemStats) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemStats.ProtoReflect.Descriptor instead.
func (*SystemStats) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{3}
}

func (x *SystemStats) GetTotalStudents() int32 {
	if x != nil {
		return x.TotalStudents
	}
	return 0
}

func (x *SystemStats) GetTotalFaculty() int32 {
	if x != nil {
		return x.TotalFaculty
	}
	return 0
}

func (x *SystemStats) GetTotalCourses() int32 {
	if x != nil {
		return x.TotalCourses
	}
	return 0
}

func (x *SystemStats) GetOpenCourses() int32 {
	if x != nil {
		return x.OpenCourses
	}
	return 0
}

func (x *SystemStats) GetTotalEnrollments() int32 {
	if x != nil {
		return x.TotalEnrollments
	}
	return 0
}

func (x *SystemStats) GetEnrollmentOpen() bool {
	if x != nil {
		return x.EnrollmentOpen
	}
	return false
}

func (x *SystemStats) GetCurrentSemester() string {
	if x != nil {
		return x.CurrentSemester
	}
	return ""
}

// Request/Response messages - Course Management
type CreateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Units         int32                  `protobuf:"varint,4,opt,name=units,proto3" json:"units,omitempty"`
	Schedule      string                 `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Room          string                 `protobuf:"bytes,6,opt,name=room,proto3" json:"room,omitempty"`
	Capacity      int32                  `protobuf:"varint,7,opt,name=capacity,proto3" json:"capacity,omitempty"`
	FacultyId     string                 `protobuf:"bytes,8,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	Semester      string                 `protobuf:"bytes,9,opt,name=semester,proto3" json:"semester,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseRequest) Reset() {
	*x = CreateCourseRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseRequest) ProtoMessage() {}

func (x *CreateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseRequest.ProtoReflect.Descriptor instead.
func (*CreateCourseRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{4}
}

func (x *CreateCourseRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *CreateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCourseRequest) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *CreateCourseRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *CreateCourseRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *CreateCourseRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateCourseRequest) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *CreateCourseRequest) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

type CreateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Course        *Course                `protobuf:"bytes,3,opt,name=course,proto3" json:"course,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCourseResponse) Reset() {
	*x = CreateCourseResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCourseResponse) ProtoMessage() {}

func (x *CreateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCourseResponse.ProtoReflect.Descriptor instead.
func (*CreateCourseResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{5}
}

func (x *CreateCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateCourseResponse) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *CreateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *CreateCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UpdateCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Units         int32                  `protobuf:"varint,4,opt,name=units,proto3" json:"units,omitempty"`
	Schedule      string                 `protobuf:"bytes,5,opt,name=schedule,proto3" json:"schedule,omitempty"`
	Room          string                 `protobuf:"bytes,6,opt,name=room,proto3" json:"room,omitempty"`
	Capacity      int32                  `protobuf:"varint,7,opt,name=capacity,proto3" json:"capacity,omitempty"`
	FacultyId     string                 `protobuf:"bytes,8,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	IsOpen        bool                   `protobuf:"varint,9,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseRequest) Reset() {
	*x = UpdateCourseRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseRequest) ProtoMessage() {}

func (x *UpdateCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseRequest.ProtoReflect.Descriptor instead.
func (*UpdateCourseRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *UpdateCourseRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateCourseRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateCourseRequest) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *UpdateCourseRequest) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *UpdateCourseRequest) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *UpdateCourseRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *UpdateCourseRequest) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *UpdateCourseRequest) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

type UpdateCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Course        *Course                `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCourseResponse) Reset() {
	*x = UpdateCourseResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCourseResponse) ProtoMessage() {}

func (x *UpdateCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCourseResponse.ProtoReflect.Descriptor instead.
func (*UpdateCourseResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *UpdateCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseRequest) Reset() {
	*x = DeleteCourseRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseRequest) ProtoMessage() {}

func (x *DeleteCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseRequest.ProtoReflect.Descriptor instead.
func (*DeleteCourseRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type DeleteCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCourseResponse) Reset() {
	*x = DeleteCourseResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCourseResponse) ProtoMessage() {}

func (x *DeleteCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCourseResponse.ProtoReflect.Descriptor instead.
func (*DeleteCourseResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *DeleteCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type AssignFacultyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	FacultyId     string                 `protobuf:"bytes,2,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignFacultyRequest) Reset() {
	*x = AssignFacultyRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignFacultyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignFacultyRequest) ProtoMessage() {}

func (x *AssignFacultyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignFacultyRequest.ProtoReflect.Descriptor instead.
func (*AssignFacultyRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{10}
}

func (x *AssignFacultyRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *AssignFacultyRequest) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

type AssignFacultyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AssignFacultyResponse) Reset() {
	*x = AssignFacultyResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AssignFacultyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AssignFacultyResponse) ProtoMessage() {}

func (x *AssignFacultyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AssignFacultyResponse.ProtoReflect.Descriptor instead.
func (*AssignFacultyResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{11}
}

func (x *AssignFacultyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AssignFacultyResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request/Response messages - User Management
type CreateUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Email         string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"` // student, faculty, admin
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	StudentId     string                 `protobuf:"bytes,4,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`  // if role=student
	FacultyId     string                 `protobuf:"bytes,5,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`  // if role=faculty
	Department    string                 `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`                 // if role=faculty
	Major         string                 `protobuf:"bytes,7,opt,name=major,proto3" json:"major,omitempty"`                           // if role=student
	YearLevel     int32                  `protobuf:"varint,8,opt,name=year_level,json=yearLevel,proto3" json:"year_level,omitempty"` // if role=student
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateUserRequest) Reset() {
	*x = CreateUserRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRequest) ProtoMessage() {}

func (x *CreateUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *CreateUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *CreateUserRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateUserRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CreateUserRequest) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *CreateUserRequest) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CreateUserRequest) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *CreateUserRequest) GetYearLevel() int32 {
	if x != nil {
		return x.YearLevel
	}
	return 0
}

type CreateUserResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Success         bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	UserId          string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	InitialPassword string                 `protobuf:"bytes,3,opt,name=initial_password,json=initialPassword,proto3" json:"initial_password,omitempty"` // displayed once
	User            *User                  `protobuf:"bytes,4,opt,name=user,proto3" json:"user,omitempty"`
	Message         string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateUserResponse) Reset() {
	*x = CreateUserResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateUserResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserResponse) ProtoMessage() {}

func (x *CreateUserResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserResponse.ProtoReflect.Descriptor instead.
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *CreateUserResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateUserResponse) GetInitialPassword() string {
	if x != nil {
		return x.InitialPassword
	}
	return ""
}

func (x *CreateUserResponse) GetUser() *User {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *CreateUserResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"` // optional filter
	ActiveOnly    bool                   `protobuf:"varint,2,opt,name=active_only,json=activeOnly,proto3" json:"active_only,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersRequest) Reset() {
	*x = ListUsersRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersRequest) ProtoMessage() {}

func (x *ListUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersRequest.ProtoReflect.Descriptor instead.
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{14}
}

func (x *ListUsersRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ListUsersRequest) GetActiveOnly() bool {
	if x != nil {
		return x.ActiveOnly
	}
	return false
}

type ListUsersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUsersResponse) Reset() {
	*x = ListUsersResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUsersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUsersResponse) ProtoMessage() {}

func (x *ListUsersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUsersResponse.ProtoReflect.Descriptor instead.
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{15}
}

func (x *ListUsersResponse) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ListUsersResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type ResetPasswordRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordRequest) Reset() {
	*x = ResetPasswordRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordRequest) ProtoMessage() {}

func (x *ResetPasswordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordRequest.ProtoReflect.Descriptor instead.
func (*ResetPasswordRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{16}
}

func (x *ResetPasswordRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ResetPasswordResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	NewPassword   string                 `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"` // displayed once
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResponse) Reset() {
	*x = ResetPasswordResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResponse) ProtoMessage() {}

func (x *ResetPasswordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResponse.ProtoReflect.Descriptor instead.
func (*ResetPasswordResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{17}
}

func (x *ResetPasswordResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordResponse) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

func (x *ResetPasswordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ToggleUserStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Activate      bool                   `protobuf:"varint,2,opt,name=activate,proto3" json:"activate,omitempty"` // true=activate, false=deactivate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleUserStatusRequest) Reset() {
	*x = ToggleUserStatusRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleUserStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleUserStatusRequest) ProtoMessage() {}

func (x *ToggleUserStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleUserStatusRequest.ProtoReflect.Descriptor instead.
func (*ToggleUserStatusRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{18}
}

func (x *ToggleUserStatusRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ToggleUserStatusRequest) GetActivate() bool {
	if x != nil {
		return x.Activate
	}
	return false
}

type ToggleUserStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleUserStatusResponse) Reset() {
	*x = ToggleUserStatusResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleUserStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleUserStatusResponse) ProtoMessage() {}

func (x *ToggleUserStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleUserStatusResponse.ProtoReflect.Descriptor instead.
func (*ToggleUserStatusResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{19}
}

func (x *ToggleUserStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToggleUserStatusResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request/Response messages - System Configuration
type SetEnrollmentPeriodRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StartDate     string                 `protobuf:"bytes,1,opt,name=start_date,json=startDate,proto3" json:"start_date,omitempty"` // ISO 8601 format
	EndDate       string                 `protobuf:"bytes,2,opt,name=end_date,json=endDate,proto3" json:"end_date,omitempty"`       // ISO 8601 format
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnrollmentPeriodRequest) Reset() {
	*x = SetEnrollmentPeriodRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnrollmentPeriodRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnrollmentPeriodRequest) ProtoMessage() {}

func (x *SetEnrollmentPeriodRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnrollmentPeriodRequest.ProtoReflect.Descriptor instead.
func (*SetEnrollmentPeriodRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{20}
}

func (x *SetEnrollmentPeriodRequest) GetStartDate() string {
	if x != nil {
		return x.StartDate
	}
	return ""
}

func (x *SetEnrollmentPeriodRequest) GetEndDate() string {
	if x != nil {
		return x.EndDate
	}
	return ""
}

type SetEnrollmentPeriodResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetEnrollmentPeriodResponse) Reset() {
	*x = SetEnrollmentPeriodResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetEnrollmentPeriodResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetEnrollmentPeriodResponse) ProtoMessage() {}

func (x *SetEnrollmentPeriodResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetEnrollmentPeriodResponse.ProtoReflect.Descriptor instead.
func (*SetEnrollmentPeriodResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{21}
}

func (x *SetEnrollmentPeriodResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SetEnrollmentPeriodResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ToggleEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enable        bool                   `protobuf:"varint,1,opt,name=enable,proto3" json:"enable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ToggleEnrollmentRequest) Reset() {
	*x = ToggleEnrollmentRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleEnrollmentRequest) ProtoMessage() {}

func (x *ToggleEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*ToggleEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{22}
}

func (x *ToggleEnrollmentRequest) GetEnable() bool {
	if x != nil {
		return x.Enable
	}
	return false
}

type ToggleEnrollmentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	EnrollmentOpen bool                   `protobuf:"varint,2,opt,name=enrollment_open,json=enrollmentOpen,proto3" json:"enrollment_open,omitempty"`
	Message        string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ToggleEnrollmentResponse) Reset() {
	*x = ToggleEnrollmentResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ToggleEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ToggleEnrollmentResponse) ProtoMessage() {}

func (x *ToggleEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ToggleEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*ToggleEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{23}
}

func (x *ToggleEnrollmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ToggleEnrollmentResponse) GetEnrollmentOpen() bool {
	if x != nil {
		return x.EnrollmentOpen
	}
	return false
}

func (x *ToggleEnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetSystemConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"` // optional, if empty returns all
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemConfigRequest) Reset() {
	*x = GetSystemConfigRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemConfigRequest) ProtoMessage() {}

func (x *GetSystemConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemConfigRequest.ProtoReflect.Descriptor instead.
func (*GetSystemConfigRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{24}
}

func (x *GetSystemConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetSystemConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Configs       []*SystemConfig        `protobuf:"bytes,1,rep,name=configs,proto3" json:"configs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemConfigResponse) Reset() {
	*x = GetSystemConfigResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemConfigResponse) ProtoMessage() {}

func (x *GetSystemConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemConfigResponse.ProtoReflect.Descriptor instead.
func (*GetSystemConfigResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{25}
}

func (x *GetSystemConfigResponse) GetConfigs() []*SystemConfig {
	if x != nil {
		return x.Configs
	}
	return nil
}

type UpdateSystemConfigRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	AdminId       string                 `protobuf:"bytes,3,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemConfigRequest) Reset() {
	*x = UpdateSystemConfigRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemConfigRequest) ProtoMessage() {}

func (x *UpdateSystemConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemConfigRequest.ProtoReflect.Descriptor instead.
func (*UpdateSystemConfigRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{26}
}

func (x *UpdateSystemConfigRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *UpdateSystemConfigRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *UpdateSystemConfigRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type UpdateSystemConfigResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateSystemConfigResponse) Reset() {
	*x = UpdateSystemConfigResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSystemConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSystemConfigResponse) ProtoMessage() {}

func (x *UpdateSystemConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSystemConfigResponse.ProtoReflect.Descriptor instead.
func (*UpdateSystemConfigResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{27}
}

func (x *UpdateSystemConfigResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateSystemConfigResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request/Response messages - Overrides
type OverrideEnrollmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"` // "force_enroll" or "force_drop"
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	AdminId       string                 `protobuf:"bytes,5,opt,name=admin_id,json=adminId,proto3" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideEnrollmentRequest) Reset() {
	*x = OverrideEnrollmentRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideEnrollmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideEnrollmentRequest) ProtoMessage() {}

func (x *OverrideEnrollmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideEnrollmentRequest.ProtoReflect.Descriptor instead.
func (*OverrideEnrollmentRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{28}
}

func (x *OverrideEnrollmentRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *OverrideEnrollmentRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *OverrideEnrollmentRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *OverrideEnrollmentRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OverrideEnrollmentRequest) GetAdminId() string {
	if x != nil {
		return x.AdminId
	}
	return ""
}

type OverrideEnrollmentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverrideEnrollmentResponse) Reset() {
	*x = OverrideEnrollmentResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverrideEnrollmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverrideEnrollmentResponse) ProtoMessage() {}

func (x *OverrideEnrollmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverrideEnrollmentResponse.ProtoReflect.Descriptor instead.
func (*OverrideEnrollmentResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{29}
}

func (x *OverrideEnrollmentResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *OverrideEnrollmentResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Request/Response messages - Statistics
type GetSystemStatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatsRequest) Reset() {
	*x = GetSystemStatsRequest{}
	mi := &file_backend_protos_admin_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatsRequest) ProtoMessage() {}

func (x *GetSystemStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatsRequest.ProtoReflect.Descriptor instead.
func (*GetSystemStatsRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{30}
}

type GetSystemStatsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Stats         *SystemStats           `protobuf:"bytes,1,opt,name=stats,proto3" json:"stats,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSystemStatsResponse) Reset() {
	*x = GetSystemStatsResponse{}
	mi := &file_backend_protos_admin_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSystemStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSystemStatsResponse) ProtoMessage() {}

func (x *GetSystemStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_admin_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSystemStatsResponse.ProtoReflect.Descriptor instead.
func (*GetSystemStatsResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_admin_proto_rawDescGZIP(), []int{31}
}

func (x *GetSystemStatsResponse) GetStats() *SystemStats {
	if x != nil {
		return x.Stats
	}
	return nil
}

var File_backend_protos_admin_proto protoreflect.FileDescriptor

const file_backend_protos_admin_proto_rawDesc = "" +
	"\n" +
	"\x1abackend/protos/admin.proto\x12\x05admin\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb6\x02\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05units\x18\x05 \x01(\x05R\x05units\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x12\x12\n" +
	"\x04room\x18\a \x01(\tR\x04room\x12\x1a\n" +
	"\bcapacity\x18\b \x01(\x05R\bcapacity\x12\x1a\n" +
	"\benrolled\x18\t \x01(\x05R\benrolled\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\n" +
	" \x01(\tR\tfacultyId\x12\x17\n" +
	"\ais_open\x18\v \x01(\bR\x06isOpen\x12\x1a\n" +
	"\bsemester\x18\f \x01(\tR\bsemester\"\xbf\x02\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05email\x18\x02 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x03 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"student_id\x18\x05 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x06 \x01(\tR\tfacultyId\x12\x1e\n" +
	"\n" +
	"department\x18\a \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05major\x18\b \x01(\tR\x05major\x12\x1d\n" +
	"\n" +
	"year_level\x18\t \x01(\x05R\tyearLevel\x12\x1b\n" +
	"\tis_active\x18\n" +
	" \x01(\bR\bisActive\x129\n" +
	"\n" +
	"created_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xb2\x01\n" +
	"\fSystemConfig\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1d\n" +
	"\n" +
	"updated_by\x18\x04 \x01(\tR\tupdatedBy\x12 \n" +
	"\vdescription\x18\x05 \x01(\tR\vdescription\"\xa2\x02\n" +
	"\vSystemStats\x12%\n" +
	"\x0etotal_students\x18\x01 \x01(\x05R\rtotalStudents\x12#\n" +
	"\rtotal_faculty\x18\x02 \x01(\x05R\ftotalFaculty\x12#\n" +
	"\rtotal_courses\x18\x03 \x01(\x05R\ftotalCourses\x12!\n" +
	"\fopen_courses\x18\x04 \x01(\x05R\vopenCourses\x12+\n" +
	"\x11total_enrollments\x18\x05 \x01(\x05R\x10totalEnrollments\x12'\n" +
	"\x0fenrollment_open\x18\x06 \x01(\bR\x0eenrollmentOpen\x12)\n" +
	"\x10current_semester\x18\a \x01(\tR\x0fcurrentSemester\"\xfe\x01\n" +
	"\x13CreateCourseRequest\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05units\x18\x04 \x01(\x05R\x05units\x12\x1a\n" +
	"\bschedule\x18\x05 \x01(\tR\bschedule\x12\x12\n" +
	"\x04room\x18\x06 \x01(\tR\x04room\x12\x1a\n" +
	"\bcapacity\x18\a \x01(\x05R\bcapacity\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\b \x01(\tR\tfacultyId\x12\x1a\n" +
	"\bsemester\x18\t \x01(\tR\bsemester\"\x8e\x01\n" +
	"\x14CreateCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12%\n" +
	"\x06course\x18\x03 \x01(\v2\r.admin.CourseR\x06course\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\x84\x02\n" +
	"\x13UpdateCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05units\x18\x04 \x01(\x05R\x05units\x12\x1a\n" +
	"\bschedule\x18\x05 \x01(\tR\bschedule\x12\x12\n" +
	"\x04room\x18\x06 \x01(\tR\x04room\x12\x1a\n" +
	"\bcapacity\x18\a \x01(\x05R\bcapacity\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\b \x01(\tR\tfacultyId\x12\x17\n" +
	"\ais_open\x18\t \x01(\bR\x06isOpen\"q\n" +
	"\x14UpdateCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x06course\x18\x02 \x01(\v2\r.admin.CourseR\x06course\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"2\n" +
	"\x13DeleteCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"J\n" +
	"\x14DeleteCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"R\n" +
	"\x14AssignFacultyRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x02 \x01(\tR\tfacultyId\"K\n" +
	"\x15AssignFacultyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe4\x01\n" +
	"\x11CreateUserRequest\x12\x14\n" +
	"\x05email\x18\x01 \x01(\tR\x05email\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"student_id\x18\x04 \x01(\tR\tstudentId\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\x05 \x01(\tR\tfacultyId\x12\x1e\n" +
	"\n" +
	"department\x18\x06 \x01(\tR\n" +
	"department\x12\x14\n" +
	"\x05major\x18\a \x01(\tR\x05major\x12\x1d\n" +
	"\n" +
	"year_level\x18\b \x01(\x05R\tyearLevel\"\xad\x01\n" +
	"\x12CreateUserResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12)\n" +
	"\x10initial_password\x18\x03 \x01(\tR\x0finitialPassword\x12\x1f\n" +
	"\x04user\x18\x04 \x01(\v2\v.admin.UserR\x04user\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"G\n" +
	"\x10ListUsersRequest\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x1f\n" +
	"\vactive_only\x18\x02 \x01(\bR\n" +
	"activeOnly\"W\n" +
	"\x11ListUsersResponse\x12!\n" +
	"\x05users\x18\x01 \x03(\v2\v.admin.UserR\x05users\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"/\n" +
	"\x14ResetPasswordRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"n\n" +
	"\x15ResetPasswordResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12!\n" +
	"\fnew_password\x18\x02 \x01(\tR\vnewPassword\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"N\n" +
	"\x17ToggleUserStatusRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bactivate\x18\x02 \x01(\bR\bactivate\"N\n" +
	"\x18ToggleUserStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"V\n" +
	"\x1aSetEnrollmentPeriodRequest\x12\x1d\n" +
	"\n" +
	"start_date\x18\x01 \x01(\tR\tstartDate\x12\x19\n" +
	"\bend_date\x18\x02 \x01(\tR\aendDate\"Q\n" +
	"\x1bSetEnrollmentPeriodResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"1\n" +
	"\x17ToggleEnrollmentRequest\x12\x16\n" +
	"\x06enable\x18\x01 \x01(\bR\x06enable\"w\n" +
	"\x18ToggleEnrollmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fenrollment_open\x18\x02 \x01(\bR\x0eenrollmentOpen\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"*\n" +
	"\x16GetSystemConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\"H\n" +
	"\x17GetSystemConfigResponse\x12-\n" +
	"\aconfigs\x18\x01 \x03(\v2\x13.admin.SystemConfigR\aconfigs\"^\n" +
	"\x19UpdateSystemConfigRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x19\n" +
	"\badmin_id\x18\x03 \x01(\tR\aadminId\"P\n" +
	"\x1aUpdateSystemConfigResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xa2\x01\n" +
	"\x19OverrideEnrollmentRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\x12\x19\n" +
	"\badmin_id\x18\x05 \x01(\tR\aadminId\"P\n" +
	"\x1aOverrideEnrollmentResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\x17\n" +
	"\x15GetSystemStatsRequest\"B\n" +
	"\x16GetSystemStatsResponse\x12(\n" +
	"\x05stats\x18\x01 \x01(\v2\x12.admin.SystemStatsR\x05stats2\xe3\b\n" +
	"\fAdminService\x12G\n" +
	"\fCreateCourse\x12\x1a.admin.CreateCourseRequest\x1a\x1b.admin.CreateCourseResponse\x12G\n" +
	"\fUpdateCourse\x12\x1a.admin.UpdateCourseRequest\x1a\x1b.admin.UpdateCourseResponse\x12G\n" +
	"\fDeleteCourse\x12\x1a.admin.DeleteCourseRequest\x1a\x1b.admin.DeleteCourseResponse\x12J\n" +
	"\rAssignFaculty\x12\x1b.admin.AssignFacultyRequest\x1a\x1c.admin.AssignFacultyResponse\x12A\n" +
	"\n" +
	"CreateUser\x12\x18.admin.CreateUserRequest\x1a\x19.admin.CreateUserResponse\x12>\n" +
	"\tListUsers\x12\x17.admin.ListUsersRequest\x1a\x18.admin.ListUsersResponse\x12J\n" +
	"\rResetPassword\x12\x1b.admin.ResetPasswordRequest\x1a\x1c.admin.ResetPasswordResponse\x12S\n" +
	"\x10ToggleUserStatus\x12\x1e.admin.ToggleUserStatusRequest\x1a\x1f.admin.ToggleUserStatusResponse\x12\\\n" +
	"\x13SetEnrollmentPeriod\x12!.admin.SetEnrollmentPeriodRequest\x1a\".admin.SetEnrollmentPeriodResponse\x12S\n" +
	"\x10ToggleEnrollment\x12\x1e.admin.ToggleEnrollmentRequest\x1a\x1f.admin.ToggleEnrollmentResponse\x12P\n" +
	"\x0fGetSystemConfig\x12\x1d.admin.GetSystemConfigRequest\x1a\x1e.admin.GetSystemConfigResponse\x12Y\n" +
	"\x12UpdateSystemConfig\x12 .admin.UpdateSystemConfigRequest\x1a!.admin.UpdateSystemConfigResponse\x12Y\n" +
	"\x12OverrideEnrollment\x12 .admin.OverrideEnrollmentRequest\x1a!.admin.OverrideEnrollmentResponse\x12M\n" +
	"\x0eGetSystemStats\x12\x1c.admin.GetSystemStatsRequest\x1a\x1d.admin.GetSystemStatsResponseB\x12Z\x10backend/pb/adminb\x06proto3"

var (
	file_backend_protos_admin_proto_rawDescOnce sync.Once
	file_backend_protos_admin_proto_rawDescData []byte
)

func file_backend_protos_admin_proto_rawDescGZIP() []byte {
	file_backend_protos_admin_proto_rawDescOnce.Do(func() {
		file_backend_protos_admin_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_protos_admin_proto_rawDesc), len(file_backend_protos_admin_proto_rawDesc)))
	})
	return file_backend_protos_admin_proto_rawDescData
}

var file_backend_protos_admin_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_backend_protos_admin_proto_goTypes = []any{
	(*Course)(nil),                      // 0: admin.Course
	(*User)(nil),                        // 1: admin.User
	(*SystemConfig)(nil),                // 2: admin.SystemConfig
	(*SystemStats)(nil),                 // 3: admin.SystemStats
	(*CreateCourseRequest)(nil),         // 4: admin.CreateCourseRequest
	(*CreateCourseResponse)(nil),        // 5: admin.CreateCourseResponse
	(*UpdateCourseRequest)(nil),         // 6: admin.UpdateCourseRequest
	(*UpdateCourseResponse)(nil),        // 7: admin.UpdateCourseResponse
	(*DeleteCourseRequest)(nil),         // 8: admin.DeleteCourseRequest
	(*DeleteCourseResponse)(nil),        // 9: admin.DeleteCourseResponse
	(*AssignFacultyRequest)(nil),        // 10: admin.AssignFacultyRequest
	(*AssignFacultyResponse)(nil),       // 11: admin.AssignFacultyResponse
	(*CreateUserRequest)(nil),           // 12: admin.CreateUserRequest
	(*CreateUserResponse)(nil),          // 13: admin.CreateUserResponse
	(*ListUsersRequest)(nil),            // 14: admin.ListUsersRequest
	(*ListUsersResponse)(nil),           // 15: admin.ListUsersResponse
	(*ResetPasswordRequest)(nil),        // 16: admin.ResetPasswordRequest
	(*ResetPasswordResponse)(nil),       // 17: admin.ResetPasswordResponse
	(*ToggleUserStatusRequest)(nil),     // 18: admin.ToggleUserStatusRequest
	(*ToggleUserStatusResponse)(nil),    // 19: admin.ToggleUserStatusResponse
	(*SetEnrollmentPeriodRequest)(nil),  // 20: admin.SetEnrollmentPeriodRequest
	(*SetEnrollmentPeriodResponse)(nil), // 21: admin.SetEnrollmentPeriodResponse
	(*ToggleEnrollmentRequest)(nil),     // 22: admin.ToggleEnrollmentRequest
	(*ToggleEnrollmentResponse)(nil),    // 23: admin.ToggleEnrollmentResponse
	(*GetSystemConfigRequest)(nil),      // 24: admin.GetSystemConfigRequest
	(*GetSystemConfigResponse)(nil),     // 25: admin.GetSystemConfigResponse
	(*UpdateSystemConfigRequest)(nil),   // 26: admin.UpdateSystemConfigRequest
	(*UpdateSystemConfigResponse)(nil),  // 27: admin.UpdateSystemConfigResponse
	(*OverrideEnrollmentRequest)(nil),   // 28: admin.OverrideEnrollmentRequest
	(*OverrideEnrollmentResponse)(nil),  // 29: admin.OverrideEnrollmentResponse
	(*GetSystemStatsRequest)(nil),       // 30: admin.GetSystemStatsRequest
	(*GetSystemStatsResponse)(nil),      // 31: admin.GetSystemStatsResponse
	(*timestamppb.Timestamp)(nil),       // 32: google.protobuf.Timestamp
}
var file_backend_protos_admin_proto_depIdxs = []int32{
	32, // 0: admin.User.created_at:type_name -> google.protobuf.Timestamp
	32, // 1: admin.SystemConfig.updated_at:type_name -> google.protobuf.Timestamp
	0,  // 2: admin.CreateCourseResponse.course:type_name -> admin.Course
	0,  // 3: admin.UpdateCourseResponse.course:type_name -> admin.Course
	1,  // 4: admin.CreateUserResponse.user:type_name -> admin.User
	1,  // 5: admin.ListUsersResponse.users:type_name -> admin.User
	2,  // 6: admin.GetSystemConfigResponse.configs:type_name -> admin.SystemConfig
	3,  // 7: admin.GetSystemStatsResponse.stats:type_name -> admin.SystemStats
	4,  // 8: admin.AdminService.CreateCourse:input_type -> admin.CreateCourseRequest
	6,  // 9: admin.AdminService.UpdateCourse:input_type -> admin.UpdateCourseRequest
	8,  // 10: admin.AdminService.DeleteCourse:input_type -> admin.DeleteCourseRequest
	10, // 11: admin.AdminService.AssignFaculty:input_type -> admin.AssignFacultyRequest
	12, // 12: admin.AdminService.CreateUser:input_type -> admin.CreateUserRequest
	14, // 13: admin.AdminService.ListUsers:input_type -> admin.ListUsersRequest
	16, // 14: admin.AdminService.ResetPassword:input_type -> admin.ResetPasswordRequest
	18, // 15: admin.AdminService.ToggleUserStatus:input_type -> admin.ToggleUserStatusRequest
	20, // 16: admin.AdminService.SetEnrollmentPeriod:input_type -> admin.SetEnrollmentPeriodRequest
	22, // 17: admin.AdminService.ToggleEnrollment:input_type -> admin.ToggleEnrollmentRequest
	24, // 18: admin.AdminService.GetSystemConfig:input_type -> admin.GetSystemConfigRequest
	26, // 19: admin.AdminService.UpdateSystemConfig:input_type -> admin.UpdateSystemConfigRequest
	28, // 20: admin.AdminService.OverrideEnrollment:input_type -> admin.OverrideEnrollmentRequest
	30, // 21: admin.AdminService.GetSystemStats:input_type -> admin.GetSystemStatsRequest
	5,  // 22: admin.AdminService.CreateCourse:output_type -> admin.CreateCourseResponse
	7,  // 23: admin.AdminService.UpdateCourse:output_type -> admin.UpdateCourseResponse
	9,  // 24: admin.AdminService.DeleteCourse:output_type -> admin.DeleteCourseResponse
	11, // 25: admin.AdminService.AssignFaculty:output_type -> admin.AssignFacultyResponse
	13, // 26: admin.AdminService.CreateUser:output_type -> admin.CreateUserResponse
	15, // 27: admin.AdminService.ListUsers:output_type -> admin.ListUsersResponse
	17, // 28: admin.AdminService.ResetPassword:output_type -> admin.ResetPasswordResponse
	19, // 29: admin.AdminService.ToggleUserStatus:output_type -> admin.ToggleUserStatusResponse
	21, // 30: admin.AdminService.SetEnrollmentPeriod:output_type -> admin.SetEnrollmentPeriodResponse
	23, // 31: admin.AdminService.ToggleEnrollment:output_type -> admin.ToggleEnrollmentResponse
	25, // 32: admin.AdminService.GetSystemConfig:output_type -> admin.GetSystemConfigResponse
	27, // 33: admin.AdminService.UpdateSystemConfig:output_type -> admin.UpdateSystemConfigResponse
	29, // 34: admin.AdminService.OverrideEnrollment:output_type -> admin.OverrideEnrollmentResponse
	31, // 35: admin.AdminService.GetSystemStats:output_type -> admin.GetSystemStatsResponse
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_backend_protos_admin_proto_init() }
func file_backend_protos_admin_proto_init() {
	if File_backend_protos_admin_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_protos_admin_proto_rawDesc), len(file_backend_protos_admin_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_protos_admin_proto_goTypes,
		DependencyIndexes: file_backend_protos_admin_proto_depIdxs,
		MessageInfos:      file_backend_protos_admin_proto_msgTypes,
	}.Build()
	File_backend_protos_admin_proto = out.File
	file_backend_protos_admin_proto_goTypes = nil
	file_backend_protos_admin_proto_depIdxs = nil
}
