// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: backend/protos/course.proto

package course

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Common messages
type Course struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code          string                 `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Units         int32                  `protobuf:"varint,5,opt,name=units,proto3" json:"units,omitempty"`
	Schedule      string                 `protobuf:"bytes,6,opt,name=schedule,proto3" json:"schedule,omitempty"` // e.g., "MWF 9:00-10:00"
	Room          string                 `protobuf:"bytes,7,opt,name=room,proto3" json:"room,omitempty"`
	Capacity      int32                  `protobuf:"varint,8,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enrolled      int32                  `protobuf:"varint,9,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	FacultyId     string                 `protobuf:"bytes,10,opt,name=faculty_id,json=facultyId,proto3" json:"faculty_id,omitempty"`
	FacultyName   string                 `protobuf:"bytes,11,opt,name=faculty_name,json=facultyName,proto3" json:"faculty_name,omitempty"` // denormalized for display
	IsOpen        bool                   `protobuf:"varint,12,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	Semester      string                 `protobuf:"bytes,13,opt,name=semester,proto3" json:"semester,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,14,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,15,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Prerequisites []string               `protobuf:"bytes,16,rep,name=prerequisites,proto3" json:"prerequisites,omitempty"` // list of course IDs
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Course) Reset() {
	*x = Course{}
	mi := &file_backend_protos_course_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Course) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Course) ProtoMessage() {}

func (x *Course) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Course.ProtoReflect.Descriptor instead.
func (*Course) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{0}
}

func (x *Course) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Course) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Course) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Course) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Course) GetUnits() int32 {
	if x != nil {
		return x.Units
	}
	return 0
}

func (x *Course) GetSchedule() string {
	if x != nil {
		return x.Schedule
	}
	return ""
}

func (x *Course) GetRoom() string {
	if x != nil {
		return x.Room
	}
	return ""
}

func (x *Course) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Course) GetEnrolled() int32 {
	if x != nil {
		return x.Enrolled
	}
	return 0
}

func (x *Course) GetFacultyId() string {
	if x != nil {
		return x.FacultyId
	}
	return ""
}

func (x *Course) GetFacultyName() string {
	if x != nil {
		return x.FacultyName
	}
	return ""
}

func (x *Course) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *Course) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

func (x *Course) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Course) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Course) GetPrerequisites() []string {
	if x != nil {
		return x.Prerequisites
	}
	return nil
}

type CourseFilter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Department    string                 `protobuf:"bytes,1,opt,name=department,proto3" json:"department,omitempty"`                      // filter by department code (e.g., "CS")
	SearchQuery   string                 `protobuf:"bytes,2,opt,name=search_query,json=searchQuery,proto3" json:"search_query,omitempty"` // search in code or title
	OpenOnly      bool                   `protobuf:"varint,3,opt,name=open_only,json=openOnly,proto3" json:"open_only,omitempty"`         // filter only open courses
	Semester      string                 `protobuf:"bytes,4,opt,name=semester,proto3" json:"semester,omitempty"`                          // filter by semester
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CourseFilter) Reset() {
	*x = CourseFilter{}
	mi := &file_backend_protos_course_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CourseFilter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CourseFilter) ProtoMessage() {}

func (x *CourseFilter) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CourseFilter.ProtoReflect.Descriptor instead.
func (*CourseFilter) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{1}
}

func (x *CourseFilter) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *CourseFilter) GetSearchQuery() string {
	if x != nil {
		return x.SearchQuery
	}
	return ""
}

func (x *CourseFilter) GetOpenOnly() bool {
	if x != nil {
		return x.OpenOnly
	}
	return false
}

func (x *CourseFilter) GetSemester() string {
	if x != nil {
		return x.Semester
	}
	return ""
}

// Request/Response messages
type ListCoursesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filters       *CourseFilter          `protobuf:"bytes,1,opt,name=filters,proto3" json:"filters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesRequest) Reset() {
	*x = ListCoursesRequest{}
	mi := &file_backend_protos_course_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesRequest) ProtoMessage() {}

func (x *ListCoursesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesRequest.ProtoReflect.Descriptor instead.
func (*ListCoursesRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{2}
}

func (x *ListCoursesRequest) GetFilters() *CourseFilter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type ListCoursesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Courses       []*Course              `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	TotalCount    int32                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCoursesResponse) Reset() {
	*x = ListCoursesResponse{}
	mi := &file_backend_protos_course_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCoursesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCoursesResponse) ProtoMessage() {}

func (x *ListCoursesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCoursesResponse.ProtoReflect.Descriptor instead.
func (*ListCoursesResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{3}
}

func (x *ListCoursesResponse) GetCourses() []*Course {
	if x != nil {
		return x.Courses
	}
	return nil
}

func (x *ListCoursesResponse) GetTotalCount() int32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetCourseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseRequest) Reset() {
	*x = GetCourseRequest{}
	mi := &file_backend_protos_course_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseRequest) ProtoMessage() {}

func (x *GetCourseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseRequest.ProtoReflect.Descriptor instead.
func (*GetCourseRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{4}
}

func (x *GetCourseRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetCourseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Course        *Course                `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseResponse) Reset() {
	*x = GetCourseResponse{}
	mi := &file_backend_protos_course_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseResponse) ProtoMessage() {}

func (x *GetCourseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseResponse.ProtoReflect.Descriptor instead.
func (*GetCourseResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{5}
}

func (x *GetCourseResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetCourseResponse) GetCourse() *Course {
	if x != nil {
		return x.Course
	}
	return nil
}

func (x *GetCourseResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CheckPrerequisitesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StudentId     string                 `protobuf:"bytes,1,opt,name=student_id,json=studentId,proto3" json:"student_id,omitempty"`
	CourseId      string                 `protobuf:"bytes,2,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPrerequisitesRequest) Reset() {
	*x = CheckPrerequisitesRequest{}
	mi := &file_backend_protos_course_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPrerequisitesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPrerequisitesRequest) ProtoMessage() {}

func (x *CheckPrerequisitesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPrerequisitesRequest.ProtoReflect.Descriptor instead.
func (*CheckPrerequisitesRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{6}
}

func (x *CheckPrerequisitesRequest) GetStudentId() string {
	if x != nil {
		return x.StudentId
	}
	return ""
}

func (x *CheckPrerequisitesRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type PrerequisiteStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	CourseCode    string                 `protobuf:"bytes,2,opt,name=course_code,json=courseCode,proto3" json:"course_code,omitempty"`
	Met           bool                   `protobuf:"varint,3,opt,name=met,proto3" json:"met,omitempty"`
	Grade         string                 `protobuf:"bytes,4,opt,name=grade,proto3" json:"grade,omitempty"` // grade received if taken
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PrerequisiteStatus) Reset() {
	*x = PrerequisiteStatus{}
	mi := &file_backend_protos_course_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrerequisiteStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrerequisiteStatus) ProtoMessage() {}

func (x *PrerequisiteStatus) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrerequisiteStatus.ProtoReflect.Descriptor instead.
func (*PrerequisiteStatus) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{7}
}

func (x *PrerequisiteStatus) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

func (x *PrerequisiteStatus) GetCourseCode() string {
	if x != nil {
		return x.CourseCode
	}
	return ""
}

func (x *PrerequisiteStatus) GetMet() bool {
	if x != nil {
		return x.Met
	}
	return false
}

func (x *PrerequisiteStatus) GetGrade() string {
	if x != nil {
		return x.Grade
	}
	return ""
}

type CheckPrerequisitesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AllMet        bool                   `protobuf:"varint,1,opt,name=all_met,json=allMet,proto3" json:"all_met,omitempty"`
	Prerequisites []*PrerequisiteStatus  `protobuf:"bytes,2,rep,name=prerequisites,proto3" json:"prerequisites,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckPrerequisitesResponse) Reset() {
	*x = CheckPrerequisitesResponse{}
	mi := &file_backend_protos_course_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckPrerequisitesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckPrerequisitesResponse) ProtoMessage() {}

func (x *CheckPrerequisitesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckPrerequisitesResponse.ProtoReflect.Descriptor instead.
func (*CheckPrerequisitesResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{8}
}

func (x *CheckPrerequisitesResponse) GetAllMet() bool {
	if x != nil {
		return x.AllMet
	}
	return false
}

func (x *CheckPrerequisitesResponse) GetPrerequisites() []*PrerequisiteStatus {
	if x != nil {
		return x.Prerequisites
	}
	return nil
}

func (x *CheckPrerequisitesResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type GetCourseAvailabilityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CourseId      string                 `protobuf:"bytes,1,opt,name=course_id,json=courseId,proto3" json:"course_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCourseAvailabilityRequest) Reset() {
	*x = GetCourseAvailabilityRequest{}
	mi := &file_backend_protos_course_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseAvailabilityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseAvailabilityRequest) ProtoMessage() {}

func (x *GetCourseAvailabilityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseAvailabilityRequest.ProtoReflect.Descriptor instead.
func (*GetCourseAvailabilityRequest) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{9}
}

func (x *GetCourseAvailabilityRequest) GetCourseId() string {
	if x != nil {
		return x.CourseId
	}
	return ""
}

type GetCourseAvailabilityResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Available      bool                   `protobuf:"varint,1,opt,name=available,proto3" json:"available,omitempty"`
	Capacity       int32                  `protobuf:"varint,2,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Enrolled       int32                  `protobuf:"varint,3,opt,name=enrolled,proto3" json:"enrolled,omitempty"`
	SeatsRemaining int32                  `protobuf:"varint,4,opt,name=seats_remaining,json=seatsRemaining,proto3" json:"seats_remaining,omitempty"`
	IsOpen         bool                   `protobuf:"varint,5,opt,name=is_open,json=isOpen,proto3" json:"is_open,omitempty"`
	Message        string                 `protobuf:"bytes,6,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetCourseAvailabilityResponse) Reset() {
	*x = GetCourseAvailabilityResponse{}
	mi := &file_backend_protos_course_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCourseAvailabilityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCourseAvailabilityResponse) ProtoMessage() {}

func (x *GetCourseAvailabilityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_protos_course_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCourseAvailabilityResponse.ProtoReflect.Descriptor instead.
func (*GetCourseAvailabilityResponse) Descriptor() ([]byte, []int) {
	return file_backend_protos_course_proto_rawDescGZIP(), []int{10}
}

func (x *GetCourseAvailabilityResponse) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *GetCourseAvailabilityResponse) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *GetCourseAvailabilityResponse) GetEnrolled() int32 {
	if x != nil {
		return x.Enrolled
	}
	return 0
}

func (x *GetCourseAvailabilityResponse) GetSeatsRemaining() int32 {
	if x != nil {
		return x.SeatsRemaining
	}
	return 0
}

func (x *GetCourseAvailabilityResponse) GetIsOpen() bool {
	if x != nil {
		return x.IsOpen
	}
	return false
}

func (x *GetCourseAvailabilityResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_backend_protos_course_proto protoreflect.FileDescriptor

const file_backend_protos_course_proto_rawDesc = "" +
	"\n" +
	"\x1bbackend/protos/course.proto\x12\x06course\x1a\x1fgoogle/protobuf/timestamp.proto\"\xf5\x03\n" +
	"\x06Course\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04code\x18\x02 \x01(\tR\x04code\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x12\x14\n" +
	"\x05units\x18\x05 \x01(\x05R\x05units\x12\x1a\n" +
	"\bschedule\x18\x06 \x01(\tR\bschedule\x12\x12\n" +
	"\x04room\x18\a \x01(\tR\x04room\x12\x1a\n" +
	"\bcapacity\x18\b \x01(\x05R\bcapacity\x12\x1a\n" +
	"\benrolled\x18\t \x01(\x05R\benrolled\x12\x1d\n" +
	"\n" +
	"faculty_id\x18\n" +
	" \x01(\tR\tfacultyId\x12!\n" +
	"\ffaculty_name\x18\v \x01(\tR\vfacultyName\x12\x17\n" +
	"\ais_open\x18\f \x01(\bR\x06isOpen\x12\x1a\n" +
	"\bsemester\x18\r \x01(\tR\bsemester\x129\n" +
	"\n" +
	"created_at\x18\x0e \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x0f \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12$\n" +
	"\rprerequisites\x18\x10 \x03(\tR\rprerequisites\"\x8a\x01\n" +
	"\fCourseFilter\x12\x1e\n" +
	"\n" +
	"department\x18\x01 \x01(\tR\n" +
	"department\x12!\n" +
	"\fsearch_query\x18\x02 \x01(\tR\vsearchQuery\x12\x1b\n" +
	"\topen_only\x18\x03 \x01(\bR\bopenOnly\x12\x1a\n" +
	"\bsemester\x18\x04 \x01(\tR\bsemester\"D\n" +
	"\x12ListCoursesRequest\x12.\n" +
	"\afilters\x18\x01 \x01(\v2\x14.course.CourseFilterR\afilters\"`\n" +
	"\x13ListCoursesResponse\x12(\n" +
	"\acourses\x18\x01 \x03(\v2\x0e.course.CourseR\acourses\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x05R\n" +
	"totalCount\"/\n" +
	"\x10GetCourseRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"o\n" +
	"\x11GetCourseResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12&\n" +
	"\x06course\x18\x02 \x01(\v2\x0e.course.CourseR\x06course\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"W\n" +
	"\x19CheckPrerequisitesRequest\x12\x1d\n" +
	"\n" +
	"student_id\x18\x01 \x01(\tR\tstudentId\x12\x1b\n" +
	"\tcourse_id\x18\x02 \x01(\tR\bcourseId\"z\n" +
	"\x12PrerequisiteStatus\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\x12\x1f\n" +
	"\vcourse_code\x18\x02 \x01(\tR\n" +
	"courseCode\x12\x10\n" +
	"\x03met\x18\x03 \x01(\bR\x03met\x12\x14\n" +
	"\x05grade\x18\x04 \x01(\tR\x05grade\"\x91\x01\n" +
	"\x1aCheckPrerequisitesResponse\x12\x17\n" +
	"\aall_met\x18\x01 \x01(\bR\x06allMet\x12@\n" +
	"\rprerequisites\x18\x02 \x03(\v2\x1a.course.PrerequisiteStatusR\rprerequisites\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\";\n" +
	"\x1cGetCourseAvailabilityRequest\x12\x1b\n" +
	"\tcourse_id\x18\x01 \x01(\tR\bcourseId\"\xd1\x01\n" +
	"\x1dGetCourseAvailabilityResponse\x12\x1c\n" +
	"\tavailable\x18\x01 \x01(\bR\tavailable\x12\x1a\n" +
	"\bcapacity\x18\x02 \x01(\x05R\bcapacity\x12\x1a\n" +
	"\benrolled\x18\x03 \x01(\x05R\benrolled\x12'\n" +
	"\x0fseats_remaining\x18\x04 \x01(\x05R\x0eseatsRemaining\x12\x17\n" +
	"\ais_open\x18\x05 \x01(\bR\x06isOpen\x12\x18\n" +
	"\amessage\x18\x06 \x01(\tR\amessage2\xdc\x02\n" +
	"\rCourseService\x12F\n" +
	"\vListCourses\x12\x1a.course.ListCoursesRequest\x1a\x1b.course.ListCoursesResponse\x12@\n" +
	"\tGetCourse\x12\x18.course.GetCourseRequest\x1a\x19.course.GetCourseResponse\x12[\n" +
	"\x12CheckPrerequisites\x12!.course.CheckPrerequisitesRequest\x1a\".course.CheckPrerequisitesResponse\x12d\n" +
	"\x15GetCourseAvailability\x12$.course.GetCourseAvailabilityRequest\x1a%.course.GetCourseAvailabilityResponseB\x13Z\x11backend/pb/courseb\x06proto3"

var (
	file_backend_protos_course_proto_rawDescOnce sync.Once
	file_backend_protos_course_proto_rawDescData []byte
)

func file_backend_protos_course_proto_rawDescGZIP() []byte {
	file_backend_protos_course_proto_rawDescOnce.Do(func() {
		file_backend_protos_course_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_backend_protos_course_proto_rawDesc), len(file_backend_protos_course_proto_rawDesc)))
	})
	return file_backend_protos_course_proto_rawDescData
}

var file_backend_protos_course_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_backend_protos_course_proto_goTypes = []any{
	(*Course)(nil),                        // 0: course.Course
	(*CourseFilter)(nil),                  // 1: course.CourseFilter
	(*ListCoursesRequest)(nil),            // 2: course.ListCoursesRequest
	(*ListCoursesResponse)(nil),           // 3: course.ListCoursesResponse
	(*GetCourseRequest)(nil),              // 4: course.GetCourseRequest
	(*GetCourseResponse)(nil),             // 5: course.GetCourseResponse
	(*CheckPrerequisitesRequest)(nil),     // 6: course.CheckPrerequisitesRequest
	(*PrerequisiteStatus)(nil),            // 7: course.PrerequisiteStatus
	(*CheckPrerequisitesResponse)(nil),    // 8: course.CheckPrerequisitesResponse
	(*GetCourseAvailabilityRequest)(nil),  // 9: course.GetCourseAvailabilityRequest
	(*GetCourseAvailabilityResponse)(nil), // 10: course.GetCourseAvailabilityResponse
	(*timestamppb.Timestamp)(nil),         // 11: google.protobuf.Timestamp
}
var file_backend_protos_course_proto_depIdxs = []int32{
	11, // 0: course.Course.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: course.Course.updated_at:type_name -> google.protobuf.Timestamp
	1,  // 2: course.ListCoursesRequest.filters:type_name -> course.CourseFilter
	0,  // 3: course.ListCoursesResponse.courses:type_name -> course.Course
	0,  // 4: course.GetCourseResponse.course:type_name -> course.Course
	7,  // 5: course.CheckPrerequisitesResponse.prerequisites:type_name -> course.PrerequisiteStatus
	2,  // 6: course.CourseService.ListCourses:input_type -> course.ListCoursesRequest
	4,  // 7: course.CourseService.GetCourse:input_type -> course.GetCourseRequest
	6,  // 8: course.CourseService.CheckPrerequisites:input_type -> course.CheckPrerequisitesRequest
	9,  // 9: course.CourseService.GetCourseAvailability:input_type -> course.GetCourseAvailabilityRequest
	3,  // 10: course.CourseService.ListCourses:output_type -> course.ListCoursesResponse
	5,  // 11: course.CourseService.GetCourse:output_type -> course.GetCourseResponse
	8,  // 12: course.CourseService.CheckPrerequisites:output_type -> course.CheckPrerequisitesResponse
	10, // 13: course.CourseService.GetCourseAvailability:output_type -> course.GetCourseAvailabilityResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_backend_protos_course_proto_init() }
func file_backend_protos_course_proto_init() {
	if File_backend_protos_course_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_backend_protos_course_proto_rawDesc), len(file_backend_protos_course_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_protos_course_proto_goTypes,
		DependencyIndexes: file_backend_protos_course_proto_depIdxs,
		MessageInfos:      file_backend_protos_course_proto_msgTypes,
	}.Build()
	File_backend_protos_course_proto = out.File
	file_backend_protos_course_proto_goTypes = nil
	file_backend_protos_course_proto_depIdxs = nil
}
